pypa/cibuildwheel

- .gitignore
- README.md
- cibuildwheel/macos.py
- test/03_before_build/environment.json
- test/03_before_build/setup.py
> before_build executes in shell

- README.md
> It's manylinux1_i686, not manylinux1_i386

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/macos.py
- test/02_test/environment.json
Fixes https://github.com/joerick/cibuildwheel/issues/39.
Let's see if this works.
> macOS: run test_command in shell

- cibuildwheel/macos.py
many bug fixes including CVE.
c.f. https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-7-final
c.f. https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-1-final
> Update Python from 3.6.6, 3.7.0 to 3.6.7, 3.7.1 on macOS

- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/03_before_build/setup.py
- test/04_build_skip/setup.py
- test/05_environment/setup.py
- test/06_docker_images/setup.py
Removals made per comments in the issue
Closes #102
> Refactoring: remove package_name

- cibuildwheel/macos.py
many bug fixes.
c.f. https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-8-final
c.f. https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-2-final
> Update Python from 3.6.7, 3.7.1 to 3.6.8, 3.7.2 on macOS

- README.md
> Add pyrogram/tgcrypto to README.md

- .travis.yml
This doesn't seem necessary anymore and greatly speeds-up ci
> Do not update brew python3

- README.md
Hi! I wanted to say how impressed I was with this tool! I'm digging into wheel-building for the first time, and while it wasn't 100% smooth I manage to do it in the first sitting, which is very impressive for how tricky a problem this is! The documentation is excellent! Keep up the good work; hope I can continue to help in some small ways.
It seems like this bullet is intended to be part of the Appveyor setup item. Right now it's coming after it in the docs and it's a bit confusing, especially when using Azure DevOps.
> Readme: Fix the outline for Appveyor setup

- test/02_test/cibuildwheel_test.py
Another test for #175 ... hopefully this fails :)
> Add check that failing tests fail on manylinux1 specifically

- README.md
- docs/setup.md
> Update doc for AppVeyor on linux

- README.md
- docs/setup.md
- examples/travis-ci-deploy-only.yml
- examples/travis-ci-test-and-deploy.yml
This is intended to close issue #223. 
The example in the README has been validated against https://github.com/joerick/cibuildwheel-autopypi-example/pull/5.
> Update travis examples

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Repeat try of download `get-pip.py` if some error occurrences.  From my observation sometimes there is network error.
> Repeat get-pip download on fail

- cibuildwheel/macos.py
- cibuildwheel/windows.py
- Update CPython 3.7 from 3.7.5 to 3.7.6
- Update CPython 3.8 from 3.8.0 to 3.8.1
> Update CPython on macOS / Windows

- cibuildwheel/linux.py
.so files might have been built for the host OS, and can cause problems inside the different OS of the docker image, as seen in #139 
This PR prints troubleshooting info if .so files are found in a project whose build failed.
Fix #139
> Raise a warning if .so files were found in a project that fails to build

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/02_test/test/spam_test.py
copy of #282 with virtualenv not forced to be bellow 20.
> change 02_test to check if virtualenv is properly used another version

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Changelog: https://docs.python.org/release/3.8.2/whatsnew/changelog.html#python-3-8-2-final
> Update CPython 3.8 from 3.8.1 to 3.8.2 on macOS/Windows

- .travis.yml
I also took the opportunity to clean up the .travis.yml a bit.
> Allow failures on s390x on Travis

- .travis.yml
Minor detail, but I'd still like to see CI pass, rather than pushing to master.
> Use yaml anchors and references to not repeat full job in allow_failures

- docs/options.md
> Add GHA example

- test/shared/utils.py
This function had grown a little unwieldy, so I took some time to refactor it. It's still a little messy, but I think it's a little better than before.
> Refactor expected_wheels test function

- appveyor.yml
APPVEYOR_CONSOLE_DISABLE_PTY, as suggested in https://github.com/appveyor/ci/issues/3376#issuecomment-611314299
> Try Appveyor config workaround

- cibuildwheel/macos.py
- cibuildwheel/windows.py
change log: https://github.com/python/cpython/blob/v2.7.18/Misc/NEWS.d/2.7.18rc1.rst
> Update CPython 2.7 from 2.7.17 to 2.7.18

- cibuildwheel/macos.py
- cibuildwheel/windows.py
https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-7-final
> Update CPython 3.7 from 3.7.6 to 3.7.7

- cibuildwheel/macos.py
- cibuildwheel/resources/pinned_docker_images.cfg
- cibuildwheel/windows.py
- unit_test/main_tests/main_options_test.py
This is still a release candidate, but let's already check if everything works and if we can remove those few workarounds! :-)
> PyPy 7.3.1

- cibuildwheel/resources/pypy3.6.patch
- cibuildwheel/windows.py
I realize that some cleaning are not done in #304
> clean after bump to pypy 7.3.1

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Changelog:
https://github.com/python/cpython/blob/v3.8.3/Misc/NEWS.d/3.8.3.rst
> Update CPython 3.8 from 3.8.2 to 3.8.3

- cibuildwheel/resources/constraints-python27.txt
- cibuildwheel/resources/constraints-python35.txt
- cibuildwheel/resources/constraints-python36.txt
- cibuildwheel/resources/constraints.txt
- cibuildwheel/resources/pinned_docker_images.cfg
Mostly to update manylinux images & check everything still works smoothely.
> Update the versions of our dependencies.

- .circleci/prepare.sh
Debugging recent linux circleCI failures
> Debug CircleCI failures

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Changelog: https://docs.python.org/release/3.7.8/whatsnew/changelog.html#changelog
> Update CPython 3.7 from 3.7.7 to 3.7.8

- cibuildwheel/windows.py
- test/test_pep518.py
Alternate version of #399  :)
I had a slightly different idea to @henryiii on this one and wanted to try it. Let's see what CI makes of it.
> Windows - distinguishing between call and shell for better arg quoting

- cibuildwheel/windows.py
- test/test_pep518.py
Testing removing shell=True for a better solution to #398. Not expected to work right away.
> WIP: Alternate version of #398

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Changelog: https://docs.python.org/release/3.8.4/whatsnew/changelog.html#changelog
> Update CPython 3.8 from 3.8.3 to 3.8.4

- cibuildwheel/bashlex_eval.py
- cibuildwheel/docker_container.py
- unit_test/environment_test.py
> Fix quotes in command in bashlex_eval

- cibuildwheel/docker_container.py
- test/test_environment.py
- unit_test/docker_container_test.py
> Fix command substitution in CIBW_ENVIRONMENT in Linux docker images

- cibuildwheel/linux.py
Due to discussion in #410 I suggest to use variable instead of repeat `/project` 7 times.
> use variable instead of '/project' literal

- cibuildwheel/linux.py
- test/test_troubleshooting.py
Adds a test for the '.so' detection and fixes a regression. See #417.
> Add troubleshoot test

- .circleci/config.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- appveyor.yml
- cibuildwheel/docker_container.py
- docs/deliver-to-pypi.md
- docs/extra.css
- docs/index.md
- setup.cfg
The pre-commit mypy support is currently broken - I've fixed it here, and used pre-commit's GitHub Action to do the check, replacing the old CircleCI check. I've also run `pre-commit autoupdate` to bump to the latest version of pre-commit hooks. I've added a few more checks (bugbear and a few more pre-commit default checkers)
> ci: format updates 

- cibuildwheel/windows.py
- test/test_pep518.py
> fix: Windows extra file

- README.md
- cibuildwheel/resources/pinned_docker_images.cfg
See also pypa/manylinux#758 and pypa/manylinux#766
> Update pinned_docker_images.cfg after the ppc64le manylinux2014 image is built again on Travis CI

- .circleci/config.yml
- .travis.yml
- README.md
- appveyor.yml
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/resources/pinned_docker_images.cfg
- cibuildwheel/windows.py
- docs/options.md
- examples/circleci-minimal.yml
- examples/travis-ci-deploy.yml
- examples/travis-ci-minimal.yml
- examples/travis-ci-test-and-deploy.yml
- test/utils.py
- unit_test/main_tests/main_options_test.py
Currently this is still `rc1`, but let's try out if things work. Only to be merged after the official final release.
> [READY] Updating PyPy to 7.3.2

- README.md
I can add https://github.com/bxlab/bx-python if that's of interest.
> Update repos using cibuildwheel

- README.md
I wish I could say I was doing something interesting with cibuildwheel, but the thing I love about it is that it just worked right out of the box! Thanks so much for building it!!
> Add coverage.py to the repos list

- README.md
@joerick I noticed the working here was a little out of date, "It can do a lot more than this project" is not very accurate anymore. I touched it up a bit, what do you think?
> docs: minor wording change for multibuild

- README.md
Closes #531
Ordering now is the same as well.
> docs: normalize CI list

- cibuildwheel/docker_container.py
Would have helped me debug an issue testing out #542, where I changed a matrix and ended up with empty image names.﻿
> fix: empty image check

- docs/options.md
> docs: note on installing for the TEST_COMMAND

- .pre-commit-config.yaml
- README.md
- docs/contributing.md
- docs/data/projects.yml
- docs/faq.md
- docs/setup.md
- examples/github-apple-silicon.yml
- examples/github-deploy.yml
- examples/github-minimal.yml
- examples/github-with-qemu.yml
- examples/travis-ci-deploy.yml
- examples/travis-ci-minimal.yml
- examples/travis-ci-test-and-deploy.yml
Some work in preparation of #575. @joerick, I've pushed this branch to the main repo to make it easy for you to build on this with the table changes and U2 mention. I've added a section that you probably could link to in the FAQs. I tried to mostly keep each change in a separate commit so you could drop one if you didn't like it. For the GitHub Action, I've moved the minimal example over to it and left the others the same - don't know what you are planning there.
- docs: tips and tricks for macOS AS
- docs: Github -> GitHub, and ensure it doesn't happen again
- examples: update GitHub examples to be a bit cleaner
- examples: bump versions in a few places
- docs: update msg about running on a development machine
- examples: move github-minimal to action
- docs: some README touchup
> docs: Universal2 discussion and more updates 

- docs/options.md
https://cibuildwheel--583.org.readthedocs.build/en/583/options/#build-skip
> docs: add missing AS indentifiers

- README.md
- docs/data/projects.yml
There was only a single setuptools rust example, that used travisci.
This is an example for github actions with multiple arches, auto release, pypi push and more!
> Add polaroid to docs/data/projects.yml

- mkdocs.yml
Enable the search box in docs
xref mondeja/mkdocs-include-markdown-plugin#24
> add search plugin

- README.md
- docs/data/projects.yml
Adding a few more from #485, also a new `pypi:` field to make #605 easier.
> docs: add PyPI field and a few more projects

- docs/contributing.md
Fixing a few out-of-date things on the contributing page of the docs
> Minor docs updates

- bin/update_pythons.py
- cibuildwheel/__main__.py
- cibuildwheel/bashlex_eval.py
- cibuildwheel/extra.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- test/test_dependency_versions.py
- unit_test/docker_container_test.py
- unit_test/main_tests/main_options_test.py
- unit_test/main_tests/main_platform_test.py
Applying some of the fixes (slightly cleaned up) as suggested  by running Sourcery.ai. See the original PR with reasoning on each change here: https://github.com/henryiii/cibuildwheel/pull/1. It _mostly_ did a pretty good job, though it liked lists over sets, and didn't handle the static type checks over sets very well. But more than 50% were nice cleanups.
Note that it produces "Black" style output for a change. PyUpgrade does too, IIRC.
> style: apply some cleanups from Sourcery.ai

- .pre-commit-config.yaml
- cibuildwheel/__main__.py
- cibuildwheel/bashlex_eval.py
- cibuildwheel/docker_container.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/test_before_all.py
Adding a few more stylistic updates.
> style: second set of updates

- bin/update_pythons.py
Overlaps a bit with #629; this currently supports updating 32-bit to 32-bit PyPy, or 64-bit to 64-bit PyPy on Windows, like CPython. Also blocks PyPy 7.3.4, since that one is broken.
> ci: fix auto-update by blocking PyPy 7.3.4

- .github/auto-merge.yml
See https://github.com/apps/mergery for more info. The label will now be called "automerge". Behaviour is simple, when the merge button is green, it presses it!﻿
> Switch to Mergery for auto-merging PRs

- examples/github-deploy.yml
Follow up on #701, missed that bit in my review & merged it...
> fix: `github-deploy.yml` example

- docs/faq.md
> docs: clarify location of dependabot file

- .pre-commit-config.yaml
- README.md
- docs/data/projects.yml
- noxfile.py
> docs: add two projects

- noxfile.py
> fix: nox `update_proj` session

- docs/options.md
Discovered this was missing in #768
> Add CPython 3.10 to docs build id table

- cibuildwheel/resources/build-platforms.toml
- cibuildwheel/resources/constraints-python36.txt
- cibuildwheel/resources/constraints-python37.txt
- cibuildwheel/resources/constraints-python38.txt
- cibuildwheel/resources/constraints-python39.txt
- cibuildwheel/resources/constraints.txt
- cibuildwheel/resources/pinned_docker_images.cfg
- docs/working-examples.md
I'm going to do a 2.1.3 release to get Python 3.10.0 out, so we don't have to wait for #854 to get that out there.
> 2.1.x Update deps

- README.md
> docs: note about musllinux mess

- .gitlab-ci.yml
Work around disk space/timeout errors.
Fixes #1025.﻿
> Reduce Gitlab testing to just the basic tests

- setup.py
Cherry-pick of 93477cab80bd0edd7f6e5cb3a7f33a46a62a69fe to benefit other PRs﻿
> Fix docs build

- docs/options.md
- setup.py
Closes #1064
This is just a quick suggestion covering the bare minimum without touching the other parts of the doc.
You guys might want to do it in a completely different way. In that case, please feel free to ignore the PR.
> docs: add note about opting into PEP 621

- README.md
- docs/data/projects.yml
- docs/working-examples.md
Updating docs with some new projects out of the 600+ projects using cibuildwheel. Based on the show and tell discussion and a sourcegraph search.
> docs: add some projects

- .travis.yml
Hopefully, this will get CI passing on TravisCI
> ci: disable travis-ci output timeout

- bin/update_virtualenv.py
See https://github.com/pypa/cibuildwheel/runs/7352553528?check_suite_focus=true.
> ci: fix update script

- test/test_environment.py
- unit_test/environment_test.py
See https://github.com/pypa/cibuildwheel/pull/1191#discussion_r928228837
> Remove dependency on Unix tools in Windows test suite

- examples/github-with-qemu.yml
- remove actions/setup-python step
- bump docker/setup-qemu-action version
closes #1202
> doc: update github-with-qemu.yml example

- .github/workflows/update-dependencies.yml
Allows to catch issues with the update workflow with related PRs.
> chore: run update workflow on pull request

- docs/data/projects.yml
Signed-off-by: Keming <kemingy94@gmail.com>
* https://github.com/tensorchord/envd
* https://github.com/mosecorg/mosec
> chore: add two ML example projects

- .github/workflows/update-dependencies.yml
The workflow should be tested in the PR due to #1210. :)
> ci: use official nox action

- README.md
🎉
@Czaki, you should now have the relevant permissions, feel free to try them out by merging this PR :)
> Add @czaki to the maintainers

- docs/changelog.md
- docs/contributing.md
- docs/cpp_standards.md
- docs/deliver-to-pypi.md
- docs/extra.css
- docs/faq.md
- docs/index.md
- docs/options.md
- docs/setup.md
- docs/theme_overrides/js/theme.js
- mkdocs.yml
- setup.py
This PR updates our docs to run on the latest version of mkdocs. 
There are quite a few extra changes to support this, because I wanted to retain the sidebar experience from the 
previous version. However, in the process of reworking that, I think I happened upon some good style 
improvements.
> Update docs toolchain

- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/options.py
- cibuildwheel/projectfiles.py
- cibuildwheel/resources/install_certifi.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
Some small cleanups inspired by `refurb`. It also doesn't like return after else, and I don't either, but left that off. :'(
> chore: minor cleanups from reverb

- docs/faq.md
> Fix docs on which dirs are mounted in container

- bin/projects.py
- docs/working-examples.md
Per comment in https://github.com/pypa/cibuildwheel/pull/1302#issuecomment-1273856532
This produces a lot of line diffs on every update and was mostly used to debug star-based sorting.
> chore: remove comment block in `docs/working-examples.md`

- docs/data/projects.yml
Add Picologging to working examples.
> Add picologging to working examples

- .gitlab-ci.yml
Gitlab Windows CI setup is broken. Let's try to fix it...
> Fix gitlab windows CI config

- CI.md
- appveyor.yml
MacOS default image has changed.
> ci: fix appveyor (Python 3.8+ needed for macOS)

- README.md
- docs/data/projects.yml
- docs/working-examples.md
> Remove pydantic from example lists

- .pre-commit-config.yaml
- cibuildwheel/__main__.py
> chore: bump to Ruff 0.0.262

- .github/workflows/test.yml
- .github/workflows/update-dependencies.yml
- .pre-commit-config.yaml
- CI.md
- action.yml
- setup.cfg
> chore: test and use 3.12 as host

- .cirrus.yml
New usage limits are now enforced on Cirrus CI: https://cirrus-ci.org/faq/#are-there-any-limits
Limit runs to the minimum.
> chore: limit Cirrus CI usage

- README.md
Matches https://github.com/pypa/cibuildwheel/pull/1705
> docs: update to readme example to `upload-artifact` v4

- pyproject.toml
Fixing a few reports from repo-review.
> chore: minor touchups to pyproject

- bin/update_docker.py
- cibuildwheel/resources/pinned_docker_images.cfg
This should fix our CI while waiting on https://github.com/pypa/manylinux/issues/1581.
> ci: pin manylinux1 with missing tag

- README.md
- docs/changelog.md
Formatting is a bit off on the RtD page.
> docs: fix formatting on changelog

- docs/data/projects.yml
[streaming-form-data](https://github.com/siddhantgoel/streaming-form-data) is a streaming parser for multipart/form-data, written in Cython.
> docs: add streaming-form-data to projects.yml

- cibuildwheel/resources/constraints.in
> chore: remove pip beta workaround

- .gitlab-ci.yml
- CI.md
- README.md
- examples/gitlab-minimal.yml
> feat: add macOS on GitLab

- pyproject.toml
Trying to fix ci; ~~might need to add `pathspec` if this isn't enough~~ (this did fix it).
> docs: bump pinned versions

- .github/workflows/test.yml
- pyproject.toml
Making sure we can run 3.13 so we can add the 3.13 classifier.
> ci: add 3.13 classifier

- .github/workflows/release.yml
- pyproject.toml
> ci: update job slightly

- docs/contributing.md
- docs/deliver-to-pypi.md
- docs/faq.md
> docs: fix typos

- docs/options.md
as mentioned in https://github.com/pypa/cibuildwheel/discussions/2129#discussioncomment-11873747
> doc: add a warning about x86-64-v2 for manylinux_2_34

- .github/workflows/test.yml
- cibuildwheel/resources/build-platforms.toml
- cibuildwheel/resources/constraints-pyodide312.txt
- cibuildwheel/resources/pinned_docker_images.cfg
To get the PyPy update on all platforms (including manylinux)
> chore(2.x): update dependencies

- cibuildwheel/options.py
- cibuildwheel/resources/constraints-pyodide312.txt
- cibuildwheel/resources/constraints-python310.txt
- cibuildwheel/resources/constraints-python311.txt
- cibuildwheel/resources/constraints-python312.txt
- cibuildwheel/resources/constraints-python313.txt
- cibuildwheel/resources/constraints-python38.txt
- cibuildwheel/resources/constraints-python39.txt
- cibuildwheel/resources/constraints.txt
- cibuildwheel/resources/pinned_docker_images.cfg
- cibuildwheel/resources/virtualenv.toml
- unit_test/options_test.py
Staging branch for the next 2.x release. 
@mayeut, just FYI I had to overwrite your change on 2.x, it seems it had been somehow fast-forward merged with `main`, so it had changes that we didn't intend to release on that branch. 
I redid the dependency update and cherry-picked the changes we wanted to release.
Opening a PR to check CI. I don't think there's anything else we want to include, but let me know if you think of something.
> V2.23.1 staging

- cibuildwheel/util.py
Backport:
* fix: always resolve the --python argument (#2328)
> [2.x] fix: always resolve --python argument (#2328)

- cibuildwheel/resources/constraints-pyodide312.txt
- cibuildwheel/resources/constraints-python310.txt
- cibuildwheel/resources/constraints-python311.txt
- cibuildwheel/resources/constraints-python312.txt
- cibuildwheel/resources/constraints-python313.txt
- cibuildwheel/resources/constraints-python39.txt
- cibuildwheel/resources/constraints.txt
- cibuildwheel/resources/nodejs.toml
- cibuildwheel/resources/pinned_docker_images.cfg
The manylinux update includes a fix for https://github.com/pypa/manylinux/issues/1760 seen in numpy testing https://github.com/numpy/numpy/issues/28570
> [2.x] Update dependencies

- cibuildwheel/platforms/linux.py
- cibuildwheel/venv.py
> fix: virtualenv 20.31 no-wheel

- README.md
It's no more cross compilation and can run tests.
> doc: update Windows ARM for GH Actions

- cibuildwheel/platforms/pyodide.py
> fix: pyodide missing wheel placeholder

- .pre-commit-config.yaml
- README.md
- bin/update_readme_options_table.py
- docs/options.md
I noticed this was out-of-date and it often is, so I wrote a script to keep it fresh. It'll run via pre-commit whenever the options.md changes.
> Update options table in README and keep up-to-date with commit hook

- README.md
- docs/contributing.md
- docs/faq.md
- docs/platforms.md
Found more to convert. Noticed it in the README, and then grepped for `CIBW_`, and found even more.
Also made a few small other tweaks, like adding tick marks, a missing `toml` highlighting, and YML -> YAML.
> docs: found more to convert to toml

- .pre-commit-config.yaml
- bin/bump_version.py
Mostly making sure a file path (docs/changelog.md) shows up, so it can be command-clicked in a terminal. Minor cleanup.
> chore: touch up release script

- cibuildwheel/platforms/android.py
See https://github.com/pybind/scikit_build_example/pull/173.
> Correct Android CMAKE_FIND_ROOT_PATH_MODE_PACKAGE value
