- cibuildwheel/linux.py
- cibuildwheel/windows.py
+ urllib2 doesn't exist in python 3 - import from urllib.request instead
+ for linux builds open docker process with universal_newlines; this
opens a pipe in 'text' mode using the default preferred encoding
> fix python 3 support

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
This commit makes 3 changes for builds on all platforms:
1) pip install of the package before the `pip wheel` command
2) add `--no-deps` to the `pip wheel` command since (1) already installs dependencies. This also avoids the additional step of building wheels for dependencies (which was the previous behavior)
3) add `--upgrade --force-reinstall --no-deps` to the pip install comand after pip wheel. This makes sure that the build still tests installing from the built wheel (which is consistent with previous behavior).
> add a 'pip install' step before building wheels

- cibuildwheel/__main__.py
- cibuildwheel/linux.py
+ In linux environment, if there was no matching python configurations for a
particular architecture (i.e. if that architecture was skipped) the docker
build script would just crash. The offending line:
for whl in /tmp/linux_wheels/*.whl; do
would result in whl being equal to the unexpanded glob expression. Rather
than checking this in the bash script, python checks whether there are any
actual wheels to build and skips the script if there are none.
+ added universal_newlines=True when making the call to grab the package name -
this fix is required for python3 since other a bytes prefix (b'') will be
added to the package name
+ In the linux/docker environment, added a try/catch statement around the
docker script for KeyboardInterrupt that will kill the docker subprocess in
cases where …
> minor fixes including python3 fix

- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
This is a WIP - there will be some tweaking but the proof of concept is there and should be fully functional. I've tested this with my package on all platforms. This should address the issue raised by PR #11 without needed an additional pip pre-install step. It also removes the step of building wheels for dependencies - a step which adds extra build time and may even cause issues for some packages. BTW this follows more closely the build steps in the https://github.com/matthew-brett/multibuild project.
Revert PR9; it was never actually needed in the first place it just fixed an
issue by side effect.
1) add --no-deps to pip wheel step in order to avoid building wheels for
dependencies. This also addresses the issues raised in PR #11.
2) Modify the pip install step across platforms to allow …
> revert PR9; add --no-deps to pip wheel; address PR11

- appveyor.yml
- cibuildwheel/__main__.py
- cibuildwheel/windows.py
Cfr. side issue in #15:
- Forcing Python on Windows to not buffer its stdout, such that the output of cibuildwheel and that of its subprocess calls is nicely interleaved.
- Changing `subprocess.check_output` to `check_call` such that the stdout of these calls is not swallowed into a never-printed string by cibuildwheel.
> Unbuffered stdout for Windows and displaying the output of subprocess calls

- cibuildwheel/__main__.py
As the title says. Reasoning for this it to e.g. have an output directory of `wheelhouse/${TRAVIS_TAG}`.
Not sure how to test this, any pointers are welcome :)
> use os.makedirs to allow nested output directory

- README.md
Added a short overview of the options cibuildwheel offers. (As proposed in #21.)
I wondered where to put it, at the start of the Options section or at the end of the Usage one. In the end I went for the latter, since after reading the 'quick start example', potential users might be wondering what is available to adapt cibuildwheel to their needs. This table then would them an idea of the kind of customizations that are provided, before actually diving into the more detailed documentation per configuration.
> Adding an overview of available options

- cibuildwheel/linux.py
I found that when installing scripts through pip (such as `pip install cmake`, for example), these scripts are not in the `PATH` when `pip wheel` is called to build the wheel.
Since OS X and Windows do have this correctly (the path just being part of the `env` dictionary), this will also increase consistency, I think
> Adding $PYBIN to path when calling pip wheel

- README.md
- cibuildwheel/linux.py
Under the assumption that https://travis-ci.org/YannickJadoul/Parselmouth/jobs/275233309 succeeds, a sillily small PR, mounting the root of the Travis CI/host file system as `/host` in the docker image for Linux builds. This allows to access directories outside of the project folder to be accessed inside of docker (e.g. the `ccache` dir that is saved/restored, in my specific use case), without big hacks (such as hard-linking that directory inside of the project root folder, or who knows what other tricks there would be).
If accepted, I still need to add some documentation in the README, perhaps.
> Adding extra mount / to /host on docker invocation for linux wheels

- cibuildwheel/macos.py
I noticed that cibuildwheel installs downloads Python and installs it even when it's already installed on Mac. That adds a lot of time to our CI, where cibuildwheel in run multiple times.
> Faster builds on Mac

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Cfr. #50
Other options would be to:
- `shell(['pip', 'wheel', '.', '-w', built_wheel_dir, '--no-deps'], env=env, cwd=project_dir)`
- `shell(['pip', 'wheel', '.', '-w', built_wheel_dir, '--no-deps', '--no-index'], env=env)`
> Fixing confusion between subdirectory and PyPI projectin call to `pip wheel <subdir>`

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- test/06_docker_images/environment.json
- test/06_docker_images/setup.py
- test/06_docker_images/spam.c
Start of #45 implementation.
Things I'm not yet happy about:
- `CIBW_MANYLINUX1_X86_64_IMAGE` and `CIBW_MANYLINUX1_I686_IMAGE` are not added to the `build_options` dictionary. Reason: passing `**build_options` to windows and mac functions would then fail (and adding the two extra arguments there does not make sense). Maybe it's time to make these build options a custom class (since the number of parameters of the `build` function starts getting quite large, too)?
- For the test, I don't have an alternative image (yet). @jbarlow83 might have one? For now, I've just looked up an alternative manylinux1 docker image, and found/used the ones from [dockcross](https://github.com/dockcross/dockcross).
> Option for alternative docker images for manylinux1

- .travis.yml
- cibuildwheel/macos.py
This PR does the following things:
- fix python3 test on macOS:
brew python formula has been updated for pyhton3, c.f. https://travis-ci.org/mayeut/cibuildwheel/builds/360577716 macOS python3 errored build
- Update python versions used to build wheels (latest binaries)
- Use latest pip:
With the new PyPI stuff on-going, pip is failing with required TLS 1.2, c.f. https://travis-ci.org/mayeut/cibuildwheel/builds/360577716 macOS python2 failing build
The job has been started in the brownout window enforcing TLS 1.2, c.f. pypa/warehouse#3411
pip 9.0.2 has been updated to support TLS 1.2 on macOS (where openSSL is too old) in pypa/pip#4454
> macOS update

- cibuildwheel/windows.py
this fixes an "ImportError: cannot import name main" when self-upgrading pip to latest version 10: https://github.com/pypa/pip/issues/5240#issuecomment-382989420
Before applying this patch, I was getting this error:
https://ci.appveyor.com/project/trufont/uharfbuzz/build/1.0.4#L91
After applying this patch (and pip installing from my cibuildwheel fork), the pip self-upgrade works and the build succeeds:
https://ci.appveyor.com/project/trufont/uharfbuzz/build/1.0.7
> windows: upgrade pip with 'python -m pip'

- README.md
- cibuildwheel/linux.py
Python 3.3 support has been dropped in pypa/manylinux@ccb88109d9fe1076cd1d8e359761644cb3010eb5
> Drop python 3.3 support on Linux

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Update setuptools on macOS/Windows
Not required on linux since the manylinux image is updated frequently
It might help with the issue seen in #63
> macOS/Windows: Update setuptools

- cibuildwheel/macos.py
Ships with an up-to-date builtin copy of OpenSSL c.f. https://www.python.org/downloads/release/python-2715/
> macOS: update to python 2.7.15

- .travis.yml
- cibuildwheel/linux.py
Give ownership of the wheel files to the current user instead of root on Linux, this also allows to cleanup the `.travis.yml` file a bit.
> Give ownership of the wheel files to the current user instead of root on Linux

- README.md
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- test/06_docker_images/environment.json
This enables building binary wheels for Python 3.7, now at its rc1 release.
It is included in the latest manylinux1 Docker image, see https://github.com/pypa/manylinux/pull/196.
Accordingly to https://www.appveyor.com/docs/build-environment/#python it is not yet available on Appveyor.
> Add support for Python 3.7

- cibuildwheel/macos.py
- test/07_ssl/setup.py
- test/07_ssl/spam.c
This is work in progress to address #70 (and #63 though the issue in this one can probably be worked around)
As of now, `cibuildwheel` uses:
- python 2.7.15 official installer, ships with OpenSSL 1.0.2o
- python 3.4.4 official installer, uses system OpenSSL 0.9.8zh
- python 3.5.4 official installer, uses system OpenSSL 0.9.8zh
- python 3.6.5 official installer, ships with OpenSSL 1.0.2n
`pip` is updated by `cibuildwheel` to the latest version and this latest now has a SecureTransport fallback implementation, thus, it works properly even when OpenSSL does not support TLS 1.2
There are now issues when building or testing wheels on macOS python 3.4 & 3.5 when build and/or test uses python ssl module (either directly or indirectly) as can be seen in #70 or #63 
The easy way would be to ask …
> macOS: patch _ssl module on Python 3.4 & 3.5

- cibuildwheel/macos.py
Update Python 3.6 from 3.6.5 to 3.6.6 on macOS
> Update Python 3.6 from 3.6.5 to 3.6.6 on macOS

- README.md
Thanks for the great work !
@joerick, `pybase64` uses `pypi deploy plugin` on `travis` which is not documented in `joerick/cibuildwheel-autopypi-example`. `python-admesh` also uses the plugin but does not build for `macOS` using `python3` which requires a trick when deploying with `pypi deploy plugin`
I can create a PR on  `cibuildwheel-autopypi-example` if you're interested in that.
> Add pybase64 to the list of working examples

- cibuildwheel/__main__.py
> Improve error reporting during package name fetching

- cibuildwheel/__main__.py
- cibuildwheel/windows.py
I have started noticing that the output from `cibuildwheel` on Travis CI is not interleaved well with the output of the subprocesses (just like on Windows/AppVeyor, see #23, #24, #26) in my build: see e.g. https://travis-ci.org/YannickJadoul/Parselmouth/jobs/410930945 (Weirdly enough, this problem does not seem to show up on the CI tests of `cibuildwheel` itself?)
By extending this fix for Windows to all platforms, the problem seems to be fixed: https://travis-ci.org/YannickJadoul/Parselmouth/jobs/411213753
> Applying unbuffered output to all platforms instead of only Windows

- cibuildwheel/linux.py
- setup.py
> Reordering the Linux docker commands to get rid of timeout logic

- README.md
Adding a link to my library that is using cibuildwheel to build linux wheels. Not currently deploying to PyPI but will soon :).
Thank you for this awesome tool.
> Add apriltags2-ethz library to readme

- cibuildwheel/macos.py
Fixes 2 low security CVE. c.f. https://www.openssl.org/news/vulnerabilities-1.0.2.html
> Update openssl patch from 1.0.2o to 1.0.2p on macOS

- cibuildwheel/linux.py
Silly thing, but Python 2.7's `subprocess.Popen` object does not have an `args` attribute, and so you now get an extra exception instead of a nice overview of the executed command, when the subprocess fails.
> Fixing "AttributeError: 'Popen' object has no attribute 'args'" on Python 2.7 for Linux builds

- cibuildwheel/__main__.py
Silly thing, but I was very confused while looking at the tests, seeing that the build options are were always in a different order (for example [here](https://ci.appveyor.com/project/joerick/cibuildwheel/builds/20661534/job/3iec2iin8gcwfr87#L1176) vs. [here](https://ci.appveyor.com/project/joerick/cibuildwheel/builds/20661534/job/3iec2iin8gcwfr87#L1609)) and this really annoys me, somehow.
The quickest solution I could think of was sorting the `build_options.items()` when printing. If this is not worth it or if there's a better order, do please tell me.
> Sorting build options dict items when printing preamble

- cibuildwheel/macos.py
Fixes 2 low security CVE. c.f. https://www.openssl.org/news/vulnerabilities-1.0.2.html
> Update openssl patch from 1.0.2p to 1.0.2q on macOS

- cibuildwheel/macos.py
Seems the fix to `pip` to #122 might still take some time to get released, and is not guaranteed to completely fix our problem. Adding `--user` to all `pip install` commands on macOS should be a harmless (?) fix to get `cibuildwheel` working again, though.
The other option would be to add `sudo` to the `pip install --upgrade setuptools` call. If you prefer that, I can change this PR.
> Running 'pip install --upgrade setuptools' with 'sudo' on macOS, fixing #122

- setup.py
One possible fix on our end for #127; see https://github.com/joerick/cibuildwheel/issues/127#issuecomment-471284771
Even if we choose to not go for this particular solution, this helps #127 and demonstrates that it's not `pip`, Travis CI, or `cibuildwheel`, but the update of `bashlex` (see https://travis-ci.org/YannickJadoul/cibuildwheel/builds/504299250 vs. https://travis-ci.org/YannickJadoul/cibuildwheel/builds/504301454).
> Fixing issue #127 by avoiding bashlex 0.13 in 'install_requires'

- cibuildwheel/macos.py
While I was looking at #127, I realized the temporary fix to #122 (which turned out to be a similar but unrelated issue) is not necessary anymore now that `pip` has been patched, fixing the issue.
If @joerick would decide to release a new version soon to include #128, then this might as well be part of it, too?
This PR would (finally!) close #122.
And, oh, yes: I've based it on #128, to get the tests green, so I'd suggest to first merge #128, and then I could rebase this PR?
> Revert temporary fix of #122

- cibuildwheel/macos.py
@joerick, if you are creating a new release anyway, then there's a new Python 2.7 version, as well.
> Updating version of Python 2.7 to 2.7.16 on macOS

- cibuildwheel/macos.py
Fixes CVE, c.f. https://www.openssl.org/news/cl102.txt
> Update openssl patch from 1.0.2q to 1.0.2r on macOS

- README.md
Thanks for your great work :slightly_smiling_face: 
Looks `0.10.1` doesn't work on Azure.
> Specify cibuildwheel=0.11 in Azure example 

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/windows.py
This is not an improvement and even less than a minor change, but incorrect spelling may be confusing. ;)
> Correct spelling: capitalized 'V' in 'AppVeyor'

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/02_test/cibuildwheel_test.py
- test/02_test/setup.py
For a number of packages I work on, the test dependencies can be installed via an [extras_require](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) option called ``test``, e.g.:
```
pip install astropy[test]
```
This PR adds support for a new environment variable ``CIBW_TEST_EXTRAS`` that can be used to make sure the wheel is installed with e.g.:
```
pip install <wheel_file>[test]
```
This then means that we can avoid duplication of listing test-time dependencies in ``CIBW_TEST_REQUIRES`` if they are already defined in ``setup.py`` or ``setup.cfg``.
Open questions:
* Does the environment variable name make sense? I was originally thinking ``CIBW_TEST_EXTRAS_REQUIRE`` but that's a bit long.
* Another approach would …
> Add support for specifying test-time dependencies via extras_require

- .circleci/config.yml
While debugging #162 I ran into an issue that the commands on CircleCI were not showing any output:
This is due to the use of the multi-line script syntax, even though all test commands are one line long, so this PR changes the commands to be on one line, allowing the output to be seen.
> Clean up CircleCI YAML syntax

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
@joerick - This is an alternative to #162 that does not use tox - however I am not able to get all the CI services to pass currently.
> Run tests in clean virtual environment [version without tox]

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- test/01_basic/cibuildwheel_test.py
- test/06_docker_images/cibuildwheel_test.py
- test/08_manylinux2010_only/cibuildwheel_test.py
- test/08_manylinux2010_only/setup.py
- test/08_manylinux2010_only/spam.c
- test/shared/utils.py
This is a bit of a (cheeky/daring?) alternative proposal for supporting `manylinux2010` and following versions ([`manylinux2014` has also been approved](https://www.python.org/dev/peps/pep-0599/), recently).
Advantages:
- The new options `CIBW_MANYLINUX_X86_64_IMAGE` and `CIBW_MANYLINUX_I686_IMAGE` provide a nice generalization and should be future-proof. Rather than adding new environment variables every time a new `manylinux` standard is released, these new options encompass both the need to switch between different `manylinux` version as well as use custom images.
- We also don't need to keep on adding new Python-platform combinations to the `python_configurations` list.
- "Building for `manylinux`" and "choosing the version of `manylinux`/using a custom image" are made independent, …
> Adding support for building manylinux2010 wheels - alternative

- test/02_test/cibuildwheel_test.py
Adds a test case for an erroring `CIBW_TEST_COMMAND`. Might shed some light / help with #175.
> Add failing test check

- .travis.yml
- README.md
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/04_build_skip/cibuildwheel_test.py
- test/shared/utils.py
Python 3.4 reached the end of its life on 16 March 2019.
It's about time to drop support for Python 3.4.
c.f. https://hugovk.github.io/drop-python/3.4/
> Drop python 3.4

- README.md
- azure-pipelines.yml
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/shared/utils.py
Just a draft to check if it works on all windows providers.
c.f. #172 for full discussion
> Adding Python 3.8, Always use nuget to install python on Windows

- azure-pipelines.yml
- setup.py
- unit_test/environment_test.py
Fixes #198 
Here's a summary of python versions / CI providers used to test `cibuildwheel`:
|               |2.7                          |3.5           |3.6          |3.7|3.8    |
|---------|------------------|----------|---------|---|------|
|windows| AppVeyor               |AppVeyor|Travis CI|      |Azure|
|linux       | TravisCI + CircleCI|Travis CI  |CircleCI |      |Azure|
|macOS  |TravisCI + CircleCI|                  |TravisCI|CircleCI|Azure|
> Tests cibuildwheel across different python versions

- cibuildwheel/linux.py
First of all, thank you for creating this project!
I'm running the latest version (master) to test my package in a virtualenv and noticed that on Linux the return code of the test isn't used. This means that the build continues even though the test command fails. This PR fixes this by keeping the return code of the test command and making that the return code of the bash script.
Note that this is not needed on mac or windows because they use ``subprocess.check_call``.
> Make sure build fails when test command fails

- cibuildwheel/windows.py
This is just preventive and does not correct any known issues.
> Use specific cibw directory on Windows to prevent collisions with installed software

- .travis.yml
Testing with python2 driver for `cibuildwheel` is already done on CircleCI.
Removing it from Travis CI speeds-up testing without reducing coverage.
Here's a summary of python versions / CI providers used to test `cibuildwheel` after this PR:
|               |2.7                          |3.5           |3.6          |3.7|3.8    |
|---------|------------------|----------|---------|---|------|
|windows| AppVeyor               |AppVeyor|Travis CI|      |Azure|
|linux       | TravisCI + CircleCI|Travis CI  |CircleCI |      |Azure|
|macOS  |                    CircleCI|                  |TravisCI|CircleCI|Azure|
> Remove macOS python2 on Travis CI

- .travis.yml
- appveyor.yml
- cibuildwheel/__main__.py
CI provider is now mostly irrelevant (#180), rework platform detection with that in mind.
Run linux test in AppVeyor.
Fixes #146 
Here's a summary of python versions / CI providers used to test `cibuildwheel` after this PR:
|               |2.7                          |3.5           |3.6          |3.7       |3.8    |
|---------|------------------|----------|---------|-------|------|
|windows| AppVeyor               |TravisCI  |               |             |Azure|
|linux       | TravisCI + CircleCI|TravisCI  |CircleCI  |TravisCI|Azure|
|macOS  |                    CircleCI|               |TravisCI |CircleCI |Azure|
> Rework platform detection to ignore CI provider.

- cibuildwheel/macos.py
- cibuildwheel/windows.py
This should get rid of the "WARNING: The scripts [...] are installed in '...' which is not on PATH." warnings (e.g., https://travis-ci.org/joerick/cibuildwheel/jobs/610081892#L636).
Moreover, since macOS and Windows had different ordering of the steps setting up the build environment (e.g., `CIBW_ENVIRONMENT` before or after the installation of `pip`), I've reordered the steps on Windows. Is this the correct order?
Alternatively, we could just silence the warnings with `--no-warn-script-location`, but fixing this (and keeping the warnings when they are relevant!) seems like a better solution.
Besides that, when do we want to use `simple_shell` vs. `shell`, @mayeut?
> Avoid script location warnings on Windows

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/options.md
to allow different options to auditwheel/delocate, alternative commands and a future Windows-equivalent.
Fix #191 .
Also fix some PEP-008 issues reported by flake8.
> Add `CIBW_REPAIR_WHEEL_COMMAND` env variable

- bin/run_test.py
- test/01_basic/cibuildwheel_test.py
- test/02_test/cibuildwheel_test.py
- test/03_before_build/cibuildwheel_test.py
- test/04_build_skip/cibuildwheel_test.py
- test/05_environment/cibuildwheel_test.py
- test/06_docker_images/cibuildwheel_test.py
- test/08_manylinux2010_only/cibuildwheel_test.py
- test/conftest.py
- test/shared/utils.py
Simpler way of getting each test to run in a unique temporary directory than #213 and #214 which also attempts to make all tests being run with a single `pytest` invocation.
> Run each test using a temporary directory

- cibuildwheel/__main__.py
- unit_test/platform_test.py
fix for
```
Traceback (most recent call last):
File "/home/czaki/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/home/czaki/.pyenv/versions/3.6.8/lib/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/home/czaki/Projekty/cibuildwheel/cibuildwheel/__main__.py", line 254, in <module>
main()
File "/home/czaki/Projekty/cibuildwheel/cibuildwheel/__main__.py", line 76, in main
if platform is None:
UnboundLocalError: local variable 'platform' referenced before assignment
```
> fix UnboundLocalError instead of proper error message

- cibuildwheel/__main__.py
- unit_test/platform_test.py
This PR cover really rare case case mentioned in #224. 
This may happen if user do some changes in `main` flow (ex set default platform) then it is possible that build will be launched. 
This PR introduces protection o two levels. Set build directory to temporary, empty dir. and monkeypatch `build`, `subprocess.Popen` and `urlopen`.  
`monkeypatch` will fail if module has no such attribute.
> Add better protection to unittest to be shure that it will create no changes on developer machine

- docs/options.md
In the documentation of `CIBW_ENVIRONMENT` there is no example with more than one environment variable.
There are some problem witch `chocolatey` service
> Add example of usage more than one environment variable

- README.md
> fix link for CIBW_BUILD_VERBOSITY in README.md

- README.md
- examples/travis-ci-deploy-only.yml
- examples/travis-ci-test-and-deploy.yml
API tokens came out of beta yesterday, so this PR fixes the examples to use those instead of PyPI passwords
https://pypi.org/help/#apitoken
Fix #154
> Switch examples to use PyPI API tokens

- cibuildwheel/__main__.py
- cibuildwheel/macos.py
- docs/cpp_standards.md
- docs/options.md
- mkdocs.yml
- test/10_cpp_standards/cibuildwheel_test.py
- test/10_cpp_standards/setup.py
- test/10_cpp_standards/spam.cpp
- test/shared/utils.py
macos below 10.6 do not support c++11 features. Next python version of pkg is 10.9. To not break backward compatibility I suggest to manually force 10.9 version
> upgrade macos version for support c++11

- test/06_docker_images/cibuildwheel_test.py
There is now a `manylinux2010-x86` dockcross image, so we can remove a few hacks :-)
> Clean up temporary workaround in test/06_docker_images/cibuildwheel_test.py

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/options.md
- test/shared/utils.py
- unit_test/main_options_test.py
- unit_test/main_util_fixtures.py
Only build x86_64 / Intel 10.9+ on macOS
> Only build x86_64 / Intel 10.9+ on macOS

- .circleci/config.yml
- .travis.yml
- CI.md
- appveyor.yml
- azure-pipelines.yml
- bin/run_test.py
- bin/run_tests.py
- cibuildwheel/__main__.py
- cibuildwheel/bashlex_eval.py
- cibuildwheel/environment.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- setup.py
- unit_test/main_util_fixtures.py
> Dropping Python 2.7 host support

- .circleci/prepare.sh
- cibuildwheel/macos.py
Isolating build issues from #185, seemingly related to virtualenv 20.
(Sorry for the PR pollution, but this might be the easiest way to test out a few things.)
> Fixing macOS CI and tests after lastest release of virtualenv

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/resources/pypy3.6.patch
- cibuildwheel/windows.py
- docs/faq.md
- docs/options.md
- test/06_docker_images/cibuildwheel_test.py
- test/08_manylinuxXXXX_only/cibuildwheel_test.py
- test/10_cpp_standards/cibuildwheel_test.py
- test/shared/utils.py
- unit_test/main_tests/main_options_test.py
There's probably still a lot to discuss on choosing defaults, option names, build tag names, ... but we can already give this a go and see if we can get the technical part working :)
Cfr. #143
> Adding PyPy support

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/05_environment/cibuildwheel_test.py
> Checking python in PATH is the one `cibuildwheel` installed/expects

- azure-pipelines.yml
- examples/azure-pipelines-minimal.yml
The 10.13 image is no longer supported and will be removed on 3/23.
Closes #276
> Bump MacOS build image on Azure Pipelines

- README.md
- examples/travis-ci-deploy-only.yml
- examples/travis-ci-test-and-deploy.yml
This ensures that the python that installs is the same python that
should execute the module (this sometimes isn't true on macOS because
the python.org installs that cibuildwheel makes take precedence over
the system versions)
Fix #266
> Change twine references to be immediately preceded by pip install in examples

- .circleci/prepare.sh
- cibuildwheel/macos.py
The issue (pypa/virtualenv#1561) was fixed by PR pypa/virtualenv#1641, and is now released in virtualenv 20.0.5. Let's undo the hack/workaround.
> Revert "Keeping virtualenv<20 on macOS, until problems get fixed by new release"

- README.md
- appveyor.yml
- docs/setup.md
- examples/appveyor-minimal.yml
Stealing @mayeut's branch that was mentioned in #225; curious to see if it now works :-)
> Add macOS support on AppVeyor

- cibuildwheel/windows.py
- docs/options.md
- test/02_test/cibuildwheel_test.py
Experiment - by removing the explicit `cmd` call for a Windows shell (we don't need this anymore since run_with_env was removed, can we chain commands on windows using `&&` or `||`, like we do on Mac/Linux.
> Allow chaining of commands on Windows

- .github/workflows/test.yml
- CI.md
- README.md
- cibuildwheel/__main__.py
- docs/setup.md
- examples/github-minimal.yml
- unit_test/main_tests/main_platform_test.py
Draft:
Closes #159
Here's a summary of python versions / CI providers used to test `cibuildwheel` after this PR:
|               |2.7                          |3.5           |3.6          |3.7       |3.8    |
|---------|------------------|----------|---------|-------|------|
|windows| AppVeyor               |TravisCI  |               |GitHub|Azure|
|linux       | TravisCI + CircleCI|TravisCI  |CircleCI  |TravisCI + GitHub |Azure|
|macOS  |                    CircleCI|               |TravisCI |CircleCI + GitHub |Azure|
> Add support for GitHub Actions

- appveyor.yml
- cibuildwheel/macos.py
- cibuildwheel/windows.py
For windows and macos extract python setup to separate function and rename `windows.shell` to `windows.call` to unify `build` function between systems.
Main advantage of this PR is separate build wheel logic from python setup logic. Build function is shorter and easier to analyse. 
This also allow to simplify user porting on CI which are not possible to test from github like gitlab (#158)
> Setup python extracted from build function

- .github/workflows/test.yml
- .travis.yml
- appveyor.yml
My PR branches get built twice on some CI services (Appveyor, Travis, Github), once for the PR and once for the branch. This disables the branch build, for anything other than master, to save some CI time.
Also, on services that support it, I've disabled docs changes from needing CI runs.
> Build PR branches only once (for origin branches) and skip docs changes

- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- unit_test/main_tests/main_options_test.py
- unit_test/main_tests/main_platform_test.py
This is PR with packing all argument of build function into single structure. This is extreme version of shortening it signature. I'm not sure if it is best solution, but also partially show how it look if there is try of introduce inheritance. 
I mark it as draft to ask you about opinion. Maybe it is better to create few structures and pack argument in few groups (like setup, test, ...).
> Pack build arguments

- cibuildwheel/linux.py
Noticed this function wasn't called anywhere - I think it got lost in a bad merge on #256. This PR adds it back.
> Add back missing 'troubleshoot' function call

- examples/travis-ci-minimal.yml
Thank you for the amazing `cibuildwheel`! :rocket: :sparkles: 
The `arch:` `aarch64` is called `arm64` on Travis-CI.
https://docs.travis-ci.com/user/multi-cpu-architectures/
Otherwise this falls back to a generic Linux amd64 host.
> Travis-CI Example: Fix aarch64

- cibuildwheel/macos.py
Update to latest 1.0.2 series (now EOL)
Unfortunately, CPython 3.5.4 doesn't seem to support 1.1.1g or I missed something: https://travis-ci.org/github/mayeut/patch-macos-python-openssl
> Update openssl patch from 1.0.2t to 1.0.2u on macOS

- docs/cpp_standards.md
What a mess.
See #325: it is sometimes possible to build C++17-only code with `MACOSX_DEOPLOYMENT_TARGET` set to a value lower than `"10.13"`.
It's horrible that there seems to be no better documentation around, and that we have to figure this out. But thinking about it further, it does make sense to me: you need a new compiler (e.g. to compile [structure bindings](https://en.cppreference.com/w/cpp/language/structured_binding)) and a new version of the standard template library (e.g., for [`std::optional`](https://en.cppreference.com/w/cpp/utility/optional)), but if neither of these require support of the C++ runtime library, after compilation an older version of OS X/macOS can still be supported.
Is this formulation clear, or will it only attract more questions/issues/...? Any …
> Updating the description of C++17 support on macOS

- mkdocs.yml
- requirements-dev.txt
I always expected URLs to be turned into hyperlinks (like on GitHub and in my IDE Markdown editors), but I noticed again that MkDocs (using Python-Markdown) doesn't do this (see e.g. https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/).
Installing and enabling this extension fixes that (and even shortens links to GitHub issues, etc, if enabled; see https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/ for details on what else can be configured).
The alternative is adding `<...>` around bare links and wouldn't require an extra extension, but that seems a lot easier to forget to me.
> Enable pymdownx.magiclink to get automatic links for URLs in the Markdown docs

- cibuildwheel/linux.py
- test/02_test/test/spam_test.py
Docker exex does not use entrypoint when using exec
https://stackoverflow.com/questions/43723777/how-to-execute-the-entrypoint-of-a-docker-images-at-each-exec-command
found in #336
> add linux32 to i686 builds

- .circleci/config.yml
- .gitignore
- .travis.yml
- CI.md
- azure-pipelines.yml
- cibuildwheel/__main__.py
- cibuildwheel/bashlex_eval.py
- cibuildwheel/environment.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- examples/travis-ci-test-and-deploy.yml
- setup.cfg
- setup.py
Finally pushing this, after this came up again in #307. As noted, this is based on an old version of master, before a bunch of refactoring PRs were merged, so it still needs to be rebased (which might be as hard as just doing it from scratch again?).
To check, install mypy and run `mypy --strict cibuildwheel/`.
Mainly meant to open the discussion of which aspects of type annoations are useful in the context of cibuildwheel and which are probably not. Python's typing is not all or nothing, so we can surely find middle ground.
@joerick, @Czaki, I think you were both interested to see this? :-)
EDIT:
Closes #258
> Add type annotations and drop Python 3.5 host support

- cibuildwheel/__main__.py
- cibuildwheel/bashlex_eval.py
- cibuildwheel/environment.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- test/12_dependency_versions/cibuildwheel_test.py
- test/shared/utils.py
- unit_test/main_tests/main_options_test.py
Now that minimum python supported is 3.6, we can use f-strings !
for tests, `setup.py` are not modified because running older python versions.
I left out 2 `.format(...)` I didn't see any interest in changing for now. 
Remaining `.format(...)` are in `linux.py`:
- in prepare_command function
- in the build function for the input string
xref #316
> Use f-strings

- cibuildwheel/resources/constraints-python27.txt
- cibuildwheel/resources/constraints-python35.txt
- cibuildwheel/resources/constraints-python36.txt
- cibuildwheel/resources/constraints.txt
- cibuildwheel/resources/pinned_docker_images.cfg
- test/test_unicode.py
If there's not a proper build isolation then, the wheel for `cp27mu` will pick up the `spam.so` built for `cp27m` resulting in an import error.
> Add test case for proper build isolation

- cibuildwheel/linux.py
See discussion in #357 and https://github.com/joerick/cibuildwheel/issues/357#issuecomment-635613056
Not entirely convinced this is the perfect solution, though, as we would also be ignoring other errors and mistakes in future commits (when e.g. a wrong container name is passed or so). One solution would be to still print the error message.
We could also make this more slightly more complex by setting `docker_image_created = True` after the `docker create` call, and only ignore the error if it's not created?
Tagging @Czaki after the discussion in #357.
> Ignore errors when cleaning up docker container in linux.py

- docs/cpp_standards.md
> Better help for GitHub Actions + Py27 workaround

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/util.py
- docs/options.md
Reducing inconsistencies about the order in which options are applied.
Arguably, `CIBW_TEST_COMMAND` could be the first one withing the "Testing" section (as it's the central goal, and the others, `CIBW_TEST_REQUIRES`, `CIBW_TEST_EXTRA`, and `CIBW_BEFORE_TEST` wouldn't be there otherwise), though chronologically, it's the last thing happening.
Any thoughts? Is this too nitpicky?
> Making order of options more consistent in docs and BuildOptions fields

- appveyor.yml
Temporarily allow this build to fail to get the tests green again
> Allow failures on Appveyor macos

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/test_testing.py
I'm curious if this will allow us to get rid of the `__CIBW_VIRTUALENV_PATH__` environment variable we always set in the test virtualenv, with the only purpose of using it in our tests.
It's not brilliantly documented, but it seems a reasonable assumption and if anything changes in future `virtualenv` releases, this is much more likely to give false negative detections (and thus fail tests when they should not, rather than vice versa).
See #283
> Simplify virtualenv test in test_testing

- .travis.yml
Thanks to @mayeut, we have a solution for the failing Windows builds on Travis CI:  'ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'
See #378 for a discussion, but I'll merge this separately (once all builds are green), such that we can rebase the other PRs :-)
> Fix SSL error on Windows on Travis CI

- test/test_projects/base.py
Fixes #372
We (probably) need to use this `__test__ = False` attribute, because it's `from .test_projects import TestProject` that causes the warning. The `test_projects` subfolder is not the issue, since `base.py` does not have the `test_` prefix.
Alternatively, we could have a `new_base_project` function, similar to `new_c_project`?
> Suppress warnings about pytest trying to collect TestProject

- bin/run_tests.py
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/mkdocs_include_markdown_plugin/mkdocs_include_markdown_plugin/plugin.py
- setup.py
- test/test_dependency_versions.py
- test/test_projects/base.py
- test/test_subdir_package.py
- test/utils.py
- unit_test/dependency_constraints_test.py
- unit_test/main_tests/conftest.py
- unit_test/main_tests/main_options_test.py
As per #316, we can now play around with `pathlib.Path` and do it safely, because:
1. Python 3.6 and above support the [file system path protocol](https://www.python.org/dev/peps/pep-0519/), so we can pass `Path` objects to old `os.path` functions, etc.
2. We have typing (let's see how much errors mypy failed to catch)
> Use pathlib.Path

- cibuildwheel/windows.py
- setup.py
- test/test_pep518.py
As discussed in #350 
I'll fix the flake8 problem after the build. Wish this used pre-commit, I checked `pre-commit run` just to see.
> Adding PEP 518 test, fix 3.5 Python on Windows

- cibuildwheel/macos.py
- cibuildwheel/windows.py
> Switch back to shutil.move from Path.rename

- cibuildwheel/macos.py
- cibuildwheel/windows.py
While working on #386 I came across a way to remove those str() calls when combining Path and str objects. The trick is to use array destructuring syntax, e.g. `['pip', 'wheel', path_object, *flags]`, rather than `+`. This way the typechecker assumes you intended to mix the types and gives you the type `List[Union[str, PathLike]]`.
> Remove str() calls in call/shell functions using destructuring syntax

- cibuildwheel/resources/pinned_docker_images.cfg
Update dependencies to get python 3.9 support on s390x
Only updating manylinux images would be enough but this also tests other updates.
> Update dependencies to get python 3.9 support on s390x

- .github/workflows/test.yml
- azure-pipelines.yml
- cibuildwheel/docker_container.py
- cibuildwheel/linux.py
- test/test_before_all.py
- test/test_before_build.py
- unit_test/docker_container_test.py
> Fix cwd in Linux docker images

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- test/test_pure_wheel.py
Fixes #255. Quick summary: non-platform wheels indicate a problem, normally because an optional extension has failed to build, or because a user misunderstands what cibuildwheel is for. This should help catch those cases.
> Raise an error when cibuildwheel produces a non-platform wheel

- docs/faq.md
A first effort to write up the Windows knowledge ﻿gathered over time, and in particular in relation to #423.
Might still need a bit of polishing, so get me some remarks! :-)
Closes #423
> Add section to the docs' FAQ about VC++ runtimes and VCRUNTIME140_1.dll on VS2019

- README.md
- docs/setup.md
- TravisCI deploy example link of docs was pointing to inexistent file.
- TravisCI config example on README didn't include the python3 link in PATH for Windows build.
> Fix TravisCI deploy example link and TravisCI config example in README

- bin/update_dependencies.py
- cibuildwheel/macos.py
- cibuildwheel/resources/constraints-python27.txt
- cibuildwheel/resources/constraints-python35.txt
- cibuildwheel/resources/constraints-python36.txt
- cibuildwheel/resources/constraints-python37.txt
- cibuildwheel/resources/pinned_docker_images.cfg
- cibuildwheel/windows.py
- docs/contributing.md
- test/test_dependency_versions.py
Python 3.9.0 was released yesterday. Nuget was fast, though Manylinux finally updated 5 hours ago ~~(do we pin a docker image? If not, this should just work?)~~. Bumping macOS and Windows to 3.9.0. The other requirements should possibly be bumped before a release is made with 3.9.0 final, I think (@joerick?).
Edit: Oops, they are pinned, just found that. Will update.
> chore: update to 3.9.0 final

- docs/options.md
Just noticed this was missing from the docs, have added it :)
> Add Python 3.9 to build identifiers table in docs

- cibuildwheel/macos.py
- cibuildwheel/resources/install_certifi.py
- Update openssl patch from 1.0.2u to 1.1.1h on macOS
- Remove python 3.5 workaround in install_certifi.py (now included in patch)
This will probably be the last update now that python 3.5 has reached End-Of-Life.
> Update openssl patch from 1.0.2u to 1.1.1h on macOS

- cibuildwheel/util.py
I found that current preamble contains:
```
dependency_constraints: <cibuildwheel.util.DependencyConstraints object at 0x10d4ca640>
```
So I add `__str__` method to DependencyConstraints class.
> Add str representation to DependencyConstraints

- README.md
Hey @joerick!
First, thank you for the amazing project! I'd like to suggest adding my package to the examples, which uses `cibuildwheel` with GitHub Actions to build binary wheels for Python 3.6+ and Linux, MacOS, and Windows.
Some notes:
- The easiest way to install and use the tool on Windows (from Python), also builds a truly native MSVC win_amd64 binary (not MinGW64).
- I couldn't find a good example of a usable CFFI cross-platform binary wheel build setup (esp. when the original C sources only build under MinGW32).
- I hope it's useful to somebody having difficulty with native Windows wheel builds. 
Cheers,
Dimiter
> Add xmlstarlet to Working examples.

- cibuildwheel/util.py
- setup.py
- unit_test/download_test.py
As [proposed](https://github.com/joerick/cibuildwheel/issues/452#issuecomment-718817456) by @jcrist, use `certifi` certificates when downloading files from host using the `download` function in `cibuildwheel/util.py`.
This behavior can be overridden using the `SSL_CERT_FILE ` environment variable.
fix #452
> Use certifi provided certificates when downloading files

- .github/workflows/test.yml
Minor thing, but this change prevents the multiple pre-commit CI runs for origin branches and prevents the 'skipped' jobs from appearing
> Improve Github triggers to prevent multiple runs on origin branches

- examples/azure-pipelines-minimal.yml
As mentioned in #205, Azure Pipelines continues to run a bash script even if a subcommand fails. To be fair, this is the default bash behaviour, but it can lead to nasty surprises (like build that report they've passed even though tests have failed). This PR adds `set -o errexit` to our examples.
Worth noting, another option would be to split these into separate actions, like
```yaml
- job: macos
pool: {vmImage: 'macOS-10.15'}
steps:
- task: UsePythonVersion@0
- bash: python3 -m pip install --upgrade pip
- bash: pip3 install cibuildwheel==1.6.4
- bash: cibuildwheel --output-dir wheelhouse .
- task: PublishBuildArtifacts@1
inputs: {pathtoPublish: 'wheelhouse'}
```
Any preference between the above and this PR?
> Use set -o errexit in the Azure example

- .circleci/config.yml
- .travis.yml
- README.md
- cibuildwheel/macos.py
- cibuildwheel/resources/pinned_docker_images.cfg
- cibuildwheel/windows.py
- docs/options.md
- examples/circleci-minimal.yml
- examples/travis-ci-deploy.yml
- examples/travis-ci-minimal.yml
- examples/travis-ci-test-and-deploy.yml
- unit_test/main_tests/main_options_test.py
The first release candidate for PyPy 7.3.3 has been released. Preparing for a hopefully painless update :-)
CC @mattip, if interested in our tests.
> Update to PyPy 7.3.3

- cibuildwheel/linux.py
- test/test_before_all.py
I think this line is missing `bin/`: https://github.com/joerick/cibuildwheel/blob/2f4ed1fafc6661b1bcfef10c28b47d593e53dfa5/cibuildwheel/linux.py#L125
First a commit to make sure I'm correct, though.
> Ensure modern version of Python in CIBW_BEFORE_ALL on manylinux

- cibuildwheel/resources/pinned_docker_images.cfg
The current pinned version of the manylinux2010 docker image has an
issue where it is trying to use EoL yum repositories
(see pypa/manylinux#836 for more details). The repository path has been
updated on the latest image. This commit bumps the manylinux2010 docker
image version to use the latest version to get this fix.
> Bump pinned default manylinux2010 image version

- README.md
- examples/travis-ci-deploy.yml
Swapping the readme example with GHA. Should we do deploy (properly) in the readme? I would rather think not, since it will make it a bit longer if we do it properly (cleaner and more modular). I've also approximately changed the Travis CI example to the correct deployment scheme. I didn't add mention of the trick I have to use to stop it from adding the SDist (important if you combine GHA + Travis for ARM, for example). Hopefully this is at least a starting point.
> docs: use GitHub example in readme

- .github/workflows/update-dependencies.yml
Per https://github.com/joerick/cibuildwheel/pull/490#issuecomment-750432177, this updates the update workflow to run weekly (manual dispatch still possible)
> Run update workflow weekly

- action.yml
- bin/bump_version.py
- docs/faq.md
- docs/setup.md
- pyproject.toml
See https://github.com/joerick/cibuildwheel/discussions/492
Demo / tested here: https://github.com/scikit-hep/boost-histogram/pull/488.
Should we update the readme and/or examples? I've updated the readme but not the examples in the current state of the PR. I think we should also add a note on how to setup dependabot to update it - I first learned about it from a different GitHub action's readme, actually. Using pinned versions but having a bot make an update PR every so often is really ideal for CI. It really helps clarify when an update breaks your CI, or when you do. :)
> feat: add support for composite-actions

- .github/workflows/test.yml
- bin/run_example_ci_configs.py
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/faq.md
- docs/options.md
- examples/github-deploy.yml
- examples/github-with-qemu.yml
- test/conftest.py
- test/test_emulation.py
- test/utils.py
- unit_test/main_tests/conftest.py
- unit_test/main_tests/main_platform_test.py
Looks like it works generally, tests are failing as we need to update expected versions, and some more
We should also discuss if we want to enable all architectures by default, or set the default to only x86/64 architectures, as this may considered a type of "breaking change".
fixes #364
> Support qemu in GitHub Actions

- cibuildwheel/macos.py
On MacOS 10.14 current patch syntax does not work (I build code with OpenMP, which needs libomp from `brew`).
> Macos patch fix

- .pre-commit-config.yaml
- cibuildwheel/bashlex_eval.py
- cibuildwheel/docker_container.py
- cibuildwheel/environment.py
- cibuildwheel/linux.py
- cibuildwheel/logger.py
- cibuildwheel/macos.py
- cibuildwheel/typing.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- setup.cfg
Discovered by #507; we are currently not actually enabling any of the settings it looks like we are enabling due to a missing `.*`. Fixes the various errors, and reworks the Colors/Symbols to be statically typeable.﻿
Adding pytest does slow down the type checking a bit; we could revert to ignoring pytest if the pre-commit run is too slow.
I've also added a py.typed file (not sure if it's in the SDist without a manifest), but it's nice to say we are typed, even if we don't really expect to be used as a library?
Could be simplified a bit by #508.
> fix: enable and fix full type checking

- .pre-commit-config.yaml
- bin/bump_version.py
- setup.py
This adds a pyupgrade check, which makes sure old-style constructs are not introduced / cleaned up. When we upgrade Python versions, we could bump the minimum here too.﻿
> style: pyupgrade

- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- setup.cfg
- unit_test/main_tests/main_platform_test.py
Followup to #482, use sets instead of lists for Archs, and make Windows handling behave more like Linux, where one arch will only use that arch. (Eventually, maybe could include ARM for windows, perhaps?).
No docs changes (yet).
I converted to sets, then added the changes from @mayeut.
> feat: Windows filtering and sets

- cibuildwheel/__main__.py
- cibuildwheel/util.py
- docs/options.md
- unit_test/main_tests/main_platform_test.py
I rather forget we already had the correct definition of "auto", but this adds the other two as mentioned in #528.
> feat: native / all archs

- .github/workflows/update-dependencies.yml
- .pre-commit-config.yaml
- bin/update_dependencies.py
- bin/update_pythons.py
- cibuildwheel/extra.py
- cibuildwheel/typing.py
- setup.cfg
- unit_test/build_ids_test.py
As mentioned in #490, a method to update CPython & PyPy on Windows/macOS.
Per @YannickJadoul criteria, the idea behind it is "clean" however, the implementation here is far from being clean and thus is opened as draft to give ideas/pointers to others as I probably won't have time to work on this.
> feat: update python versions as part of update_dependencies

- cibuildwheel/util.py
- docs/options.md
- setup.cfg
- unit_test/build_selector_test.py
This adds support for `{}`.
TODO for getting this ready:
- Add a javascript version to the docs. [This looks pretty close](https://github.com/grob/fnmatch), actually. We can also iterate on [my demo](https://jsfiddle.net/henryiii/btuon0hy/1/show). (separate PR)
> feat: support brace expansion in BUILD/SKIP

- bin/bump_version.py
- bin/make_dependency_update_pr.py
- bin/run_example_ci_configs.py
- bin/sample_build.py
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
Changes some raw uses of `exit()` to either `sys.exit` or `raise Exit` from click. Just a correctness fix (unless site.py is not loaded).
> fix: improve correctness of exits

- action.yml
- docs/faq.md
This fixes the action so that it runs regardless of whether setup-python has been called first, on all runners except ubuntu 16.04. ~~on ubuntu-20.04 or macos-latest (it always worked on windows-latest). It does not fix ubuntu-18.04 (ubuntu-latest), but hopefully that will become 20.04 soon.~~
~~I'm not proposing we change the directions, just make it more likely to work if someone doesn't follow them.~~
> fix: action still runs if setup-python is not called

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/options.md
Addressing #529 (no universal yet, but that can be added when #484 is in). Just a SKIP, since that seemed to be the consensus? Without the `!` syntax in BUILD I guess only SKIP makes sense (though it is very easy to add).
> feat: CIBW_TEST_SKIP

- README.md
- docs/data/projects.yml
Adding a missing `CIBW_ARCHS_LINUX` line, as well as updating from #485. Also adding a pointer to the discussion for cibuildwheel example projects.
> docs: update for some new packages

- cibuildwheel/__main__.py
- cibuildwheel/architecture.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/setup.md
- pyproject.toml
- test/test_cpp_standards.py
- test/test_dependency_versions.py
- test/utils.py
- unit_test/main_tests/conftest.py
- unit_test/main_tests/main_options_test.py
- unit_test/main_tests/main_platform_test.py
This adds an error message and exit code if no build selectors match, catching runs that don't actually build anything at all. I think this came up once before? Can't find it now. Hopefully the conclusion was it was a good idea?
#536 could build on this and print a smart error message if it's the requires-python part causing it to be empty.
This uncovered a few issues in testing, most importantly that `test_cpp17_py27_modern_msvc_workaround` passes even if not supported, since it's comparing an empty set with an empty set. I've allowed Travis to participate in the MSVC workaround to fix it.
> feat: error if empty build selection, Travis 2.7 Win w/ workaround

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/architecture.py
- docs/options.md
- unit_test/main_tests/main_platform_test.py
Add `auto32`/`auto64`.
Closes #551.
> feat: auto32/auto64

- .pre-commit-config.yaml
- bin/update_pythons.py
- pyproject.toml
- setup.cfg
Fixes issues seen in #572
Small cleanup tweaks to black and MyPy, to make running by hand a little easier.
> fix: updates should include universal2 Pythons

- cibuildwheel/__main__.py
- cibuildwheel/util.py
- unit_test/main_tests/conftest.py
- unit_test/main_tests/main_requires_python_test.py
- unit_test/test_wheel_print.py
This adds a printout after cibuildwheel runs to list exactly what changes. Serves as a good way to check to see exactly what built, and should show if any (un)expected extra files show up.
Closes #566
> feat: print new files after building

- .gitignore
- .pre-commit-config.yaml
- .readthedocs.yml
- docs/options.md
- examples/github-deploy.yml
- examples/github-minimal.yml
- examples/github-with-qemu.yml
- requirements-dev.txt
- setup.cfg
- setup.py
Adding three things (one commit each):
* Support for `[docs]` and `[test]` extras, allowing these to be installed individually. Dev no longer includes the docs requirements (but the requirements-dev file does both for you, just like before). Simplifies RtD build a little bit. Bumped the pinned versions of docs requirements. Edit: `[test]` not `[tests]`, more common (checked Pandas).
* Bump to showing the 20.04 images, since the default should be changing soon. (GHA only, not sure about Azure or others)
* ~~Support nested markdown in other constructs. @joerick I think there might be one other place where this was needed?~~ Removed for now, might be ruining styling
> docs: cleanup

- cibuildwheel/__main__.py
Adding a blank line before the printout from #570; the new printout is fantastic and useful, but a little crowded onto the other printouts, which all have a blank line spacing.
> fix: add a blank line for better visual spacing

- README.md
These were not rendering correctly:
> docs: fix bullets in 1.6.0 release notes

- test/test_docker_images.py
Fixing our tests, stage 1. Stage 2 will be when we update our docker images. We might want to pin to the last manylinux2010 with Python2 for the cibuildwheel 1.9.x series. The next release could drop Python 2 when building with manylinux2010, just like 2014 does now, I believe.
> tests: don't expect CPython 2.7 in manylinux2010 images

- cibuildwheel/__main__.py
Mentioned in #587 - currently, there's an asymmetry between not setting `CIBW_BUILD`, and setting it to "", that can be surprising, especially in a matrix. This treats an empty string the same way as being undefined.
> fix: empty CIBW_BUILD should still count as "*"

- README.md
Followup to #581 fixing two more release notes. The fence should be fixed by #576.
> docs: fix a few more markdown spaces missing

- cibuildwheel/macos.py
Looking at it, I think just a simple fix is likely okay; there's not a way to combine these easily, and it's a bit specific to this one variable. Fixes #563.
> fix: set MACOSX_DEPLOYMENT_TARGET for BEFORE_ALL

- docs/extra.css
- docs/extra.js
- docs/faq.md
- docs/options.md
- docs/setup.md
- mkdocs.yml
- setup.py
This is a rough draft example of what tabs would look like. I've applied it to one place (GHA example), and the implementation is highly manual and not reusable, so will need to be improved if we want to go this way (@joerick might be able to be a lot more elegant at this than me :), or maybe there's a built-in tool somewhere (though I think we would need to support super fences, which we don't yet). Previously mentioned here: https://github.com/joerick/cibuildwheel/pull/567#issuecomment-770572043
Thoughts? [Visit the RtD PR check to view the docs, setup page](https://cibuildwheel--576.org.readthedocs.build/en/576/setup/). I've recently added tabs here: https://packaging.python.org/tutorials/packaging-projects/#configuring-metadata (though that was in sphinx).
> docs: support tabs

- bin/run_tests.py
- bin/update_dependencies.py
- cibuildwheel/bashlex_eval.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/test_macos_archs.py
- test/test_projects/__main__.py
- test/utils.py
In Python 3.5+, `run` is [recommended](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module) over `check_*`. This converts to using the newer syntax, as well as catches two issues: `check_call` either returns 0 or throws an error, so the return int functions were misleading. And there was a case of `check_output` that was not using the output. (If it was meant to hide the output, I can tell it to do that via run).
- change check_call to run
- refactor: change check_output to run
> refactor: subprocess.run

- .github/workflows/update-dependencies.yml
- bin/update_dependencies.py
- cibuildwheel/resources/pinned_docker_images.cfg
`manylinux2010` dropped CPython 2.7
Use the tag `2021-02-06-3d322a5` which is the last supporting CPython 2.7
> Pin `manylinux2010` images (CPython 2.7 support)

- bin/update_pythons.py
Should fix the update script (as seen in #610)
> fix: macos11 universal naming corrected

- .github/workflows/test.yml
This check was the same as the check performed by pre-commit.ci, except that the pre-commit.ci is a bit faster and can fix some issues itself, so I'm removing the GHA one in favour of the pre-commit.ci one.
> Make GHA pre-commit check a precursor to main test

- cibuildwheel/windows.py
Windows does not have 'which' command, it should be 'where' command.
> Bug fix: windows does not have 'which' command

- .github/workflows/test.yml
- .travis.yml
- README.md
- azure-pipelines.yml
- cibuildwheel/windows.py
- docs/cpp_standards.md
- docs/setup.md
- examples/azure-pipelines-minimal.yml
- examples/github-deploy.yml
- examples/github-minimal.yml
- examples/github-with-qemu.yml
- examples/travis-ci-deploy.yml
- examples/travis-ci-minimal.yml
- examples/travis-ci-test-and-deploy.yml
- test/test_dependency_versions.py
- test/utils.py
Hoping to fix the issues seen in current CI runs. At the very least, we will follow the style guide linked below.
Following https://docs.chocolatey.org/en-us/choco/commands/#scripting-integration-best-practices-style-guide
* Avoid `-f` in scripts
* Always use `-y` in scripts
* Use `upgrade` instead of `install` in scripts
* Use `--limit-output` for more parsable output (should turn off progress bar as well, hopefully)
The issue with vcpython27 might be temporary, caused by the -f, or possibly permanent since it has been untouched since 2016.
> ci: fix choco usage

- .pre-commit-config.yaml
- pyproject.toml
- setup.cfg
I found (from pypa/build) a way to enforce blackwards quotes (single quotes instead of double quotes). Black's argument (in English, single quotes are more common, so using double quotes avoids escaping as often) is reasonable, though I really just like a standard regardless of which one, and black is reasonable. But if we are going with single quotes (for now?), let's be consistent. (And it's mostly my fault that we are not, I think, because I revert to blackish).
Also adding a few extra pre-commit checks, and _almost_ applying consistent styling in pre-commit to setup.cfg - the parser loses comments, so can't activate it as as default check.
Look at the changes by commit for easier review.
> refactor: string and setup.cfg normalization

- .travis.yml
- cibuildwheel/windows.py
Fix this error on Travis:
> Package 'pythonx86 3.5.4' is not found in the following primary source(s): 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'. Please verify all your online package sources are available (OR) package id, version are specified correctly
The problem seems to be that Travis added a blank nuget config file at `%AppData%\NuGet\NuGet.Config`, so nuget didn't know where to fetch its packages from. This PR adds a `FallbackSource` via the command line, so regardless of config files, nuget can find the registry.
> Fix nuget error on Travis

- bin/update_dependencies.py
> fix: missing f for fstrings in bin

- .github/workflows/test.yml
I think the custom action predates the native syntax? Besides removing a requirement, this also should get around the "snapshot" issue seen in #541; the native syntax should allow you to add the label and retrigger the build, while the custom action doesn't let you retrigger with new labels.
> ci: use native actions syntax

- bin/update_pythons.py
macosx11 installer requires macOS 11+ for CPython 3.8 while macosx11 installer for CPython 3.9+ only requires macOS 10.9+ on x86_64.
c.f. comments in #663
> pin CPython 3.8 installer on macosx10.9

- cibuildwheel/resources/pinned_docker_images.cfg
Using the final 3.5 pinned images as mentioned by @mayeut.
> [1.x] chore: bump to final Python 3.5 pin

- .circleci/config.yml
I'm still waiting to hear back from CircleCI about the Mac builds, so I'm disabling this for now.
> Temporarily disable CircleCI mac 

- .travis.yml
- CI.md
- README.md
- docs/setup.md
- examples/travis-ci-deploy.yml
- examples/travis-ci-minimal.yml
- examples/travis-ci-test-and-deploy.yml
Leaving macOS results in an "Not enough credits" on travis-ci.com
> Remove macOS build on travis-ci

- .travis.yml
- examples/travis-ci-deploy.yml
- examples/travis-ci-minimal.yml
- examples/travis-ci-test-and-deploy.yml
- test/test_manylinuxXXXX_only.py
- Disable manylinux only tests on Travis CI ppc64le
Those tests are taking too much disk space for the Travis CI runner right now.
c.f. https://travis-ci.community/t/running-out-of-disk-space-quota-when-using-docker-on-ppc64le/11634
- Use focal to run aarch64/ppc64le/s390x jobs on Travis CI
This removes allow_failures from the Travis CI s390x job which used a buggy xenial image.
> Fix Travis CI tests on ppc64le/s390x

- .circleci/config.yml
This reverts commit af45aface9ca3366b7a75148dcd62b8ffb9640ce.
> Revert "Temporarily disable CircleCI mac builds (#685)"

- bin/update_dependencies.py
- docs/contributing.md
The current docker command doesn't work.
For Python 3.6, the `manylinux{1,2010,2014}` images have an ~~incorrectly configured encoding~~, so click just crashes with complaints about the encoding. `manylinux_2_24` doesn't have this issue. (It's also more compatible == better for _running_ wheels) This was in #661 but got changed to manylinux2010 before merging. EDIT: No, it was forcing the locale to one that was missing; removing that fixes it. I still think this might be a slightly better image?
Second, the paths printed out in the constraint files are wrong - they have a `/src` added to them. Fixed, and setting the working directory makes the docker line a little simpler, I think.
> fix: docker run example and requirements paths

- README.md
This changes the blank cell to N/A, since arm64 is not natively supported on
those versions of Python.
Shoutout to @pganssle for noting that this would be useful in https://twitter.com/pganssle/status/1397271016536252421, and @FFY00 for coming up with "N/A" as a choice for phrasing that.
> Clarify Apple Silicon support on various Python versions

- cibuildwheel/__main__.py
- unit_test/main_tests/main_options_test.py
Dropping the old check, and adding a new one for `p2` or `p35` in selectors.
Not sure if this is a "fix", "feat", or "chore". 😜
> feat: update deprecated option check

- .travis.yml
These fail a lot, so maybe using the new Graviton's would be better? Just trying it out.
See https://blog.travis-ci.com/2020-09-11-arm-on-aws  and https://docs.travis-ci.com/user/multi-cpu-architectures
> ci: try Travis AWS arm64-graviton2

- README.md
- cibuildwheel/macos.py
- cibuildwheel/resources/build-platforms.toml
This adds support for creating wheels with CPython 3.8 for Apple Silicon. This is significant because 3.8 is the default Python on macOS's Xcode CLT.
---
Orignal message:
This currently produces an "x86_64" tagged wheel instead of the correct universal2 tag (but the wheel is fine if you rename it, other than having the wrong tag also listed in WHEEL). See https://github.com/scipy/oldest-supported-numpy/pull/20 and grab example wheels at https://github.com/scikit-hep/boost-histogram/pull/583.﻿
> feat: support building universal/arm64 from x64_86 Python 3.8

- docs/faq.md
Python 3.8+ supports this now. Unlikely to ever be back-ported further.
> docs: update wording on AS

- README.md
- cibuildwheel/__main__.py
- cibuildwheel/options.py
- cibuildwheel/resources/defaults.toml
- docs/extra.css
- docs/extra.js
- docs/options.md
- unit_test/main_tests/main_options_test.py
- unit_test/options_toml_test.py
Closes #547.
Design:
`tool.cibuildwheel` holds options with a structure that exactly matches the environment variables, just with dashes used instead of `_` to match TOML style. `tool.cibuildwheel.<platform>` holds the platform specific commands; these are identical but override the global value if defined and running on that platform. The defaults are defined in `cibuildwheel/resources/defaults.toml`. Environment variables override the pyproject.toml values, which override the defaults.toml values. An error is thrown if an unexpected option is found inside `tool.cibuildwheel` or a section based on what was found in the defaults.toml file.
`CIBW_PROJECT_REQUIRES_PYTHON` does not participate, since it has a canonical location in the pyproject.toml file already, and `CIBW_PLATFORM` really …
> feat: configuration support

- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/resources/defaults.toml
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/options.md
- test/conftest.py
- test/test_0_basic.py
- test/test_before_build.py
- test/test_dependency_versions.py
- test/test_pep518.py
- test/test_troubleshooting.py
> feat: support pypa build

- action.yml
This should fix #587, at least from the GitHub Action. AFAICT, logging in GHA does not show stdout vs stderr, and they are interleaved incorrectly anyway.
> fix(action): Output a single stream

- .pre-commit-config.yaml
- bin/update_pythons.py
- setup.py
Requires packaging>=21.0
This allows to simplify a bit `bin/update_pythons.py` with regards to typing.
> chore: update packaging dev requirement

- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/test_dependency_versions.py
> fix: support space in constraints file path

- .circleci/config.yml
- examples/circleci-minimal.yml
This closes #745. I think we should probably recommend the latest image supported rather than the oldest image supported, similar to other platforms (and would be needed for things like Apple Silicon support anyway), but this PR has the minimum required change.
> ci: fix circle ci image

- action.yml
Fixing #752. Have no idea why this is broken, but it seems to be broken. Switching to bash fixes it. I'm not sure if we need the `2>&1` in bash;  was the interleaving only showing up in the action (powershell)? Given that redirection was buggy, maybe the output was too?
> fix(action): use bash instead of powershell

- docs/options.md
Also includes a typo fix.
Closes #755.
> docs: multiline examples

- docs/options.md
On Windows you often find directories containing spaces. The relation
between quotes and escaping is not intuitive, see #765.
> Add an example of PATH customisation on Windows

- cibuildwheel/util.py
- unit_test/build_selector_test.py
Python 3.10 is [now ABI stable](https://www.python.org/downloads/release/python-3100rc1/), and the core devs are calling for packagers to prepare for 3.10 compatibility, so we're bringing 3.10 out from behind the PRERELEASE_PYTHONS flag. Let see if the tests still pass!
> Bring 3.10 out of prerelease

- .github/workflows/update-dependencies.yml
Currently this is run also on forks, where it fails at the generate-token step.
> Update dependencies workflow only on pypa repo

- cibuildwheel/linux.py
- test/test_troubleshooting.py
> Improve diagnostics when auditwheel repair fails

- docs/faq.md
As discussed in #816.
Fixes #816.
> Add docs entry regarding DYLD_LIBRARY_PATH

- bin/run_tests.py
- setup.py
This revisits #412.
With musllinux around the corner, CI times are growing quite a bit.
This does not apply to Windows/macOS (yet) for the reasons outlined in #412.
> feat(CI): run linux tests with pytest-xdist

- bin/run_tests.py
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/options.py
- cibuildwheel/util.py
In working on #799, it is very important to have the code better factorized so that I can apply the changes needed there. I've pulled out just the cleanup (so far) and will present that to keep the changes from being too large, and to allow this to be evaluated on its own.
Features:
* Pulled most of the options configuration out of `__main__.py` and placed it in a function in `options.py:compute_options`. This will be refactored in the future to be run on each `override` (which explains why some non-overridable options are not part of this function). This also improves the separation of the code, "main" stuff like paths is better separated from options handling.
* Architecture lists are placed in `util.py` instead of `__main__.py`.
* Stringization is moved to `BuildOptions`. Eventually, …
> refactor: better code factorization

- .pre-commit-config.yaml
- pyproject.toml
This automatically cleans up unused imports, for faster development than just having flake8 complain at you and tell you to do completely trivial work.
> chore: add pycln to pre-commit

- docs/changelog.md
- docs/deliver-to-pypi.md
Upon browsing the docs, I noticed that in the [Automatic section of the Deliver to PyPI docs](https://cibuildwheel.readthedocs.io/en/stable/deliver-to-pypi/#automatic-method), the link to the example repo is broken. It seems 3be2d0c indiscriminately converted all references to joerick/cibuildwheel to pypa/cibuildwheel, including those to other repositories with names starting with `cibuildwheel` that were not being moved. Upon checking that commit, I noticed at least one other link that was broken as well, and given it was a rather trivial, straightforward change, went ahead and fixed both in a PR.
NB, link breakage like this could be fixed by a `linkcheck` tool in your CIs; I'm not really familiar with the mkdocs ecosystem as opposed to Sphinx, but at least at a glance, it seems …
> Fix broken links incorrectly converted to point to PyPA org

- docs/deliver-to-pypi.md
- examples/github-deploy.yml
- examples/travis-ci-test-and-deploy.yml
> docs: better deployment docs

- .pre-commit-config.yaml
Re-enabling [Pycln ](https://github.com/hadialqattan/pycln) after solving the Python3.10 artificial limitation issue.
___
This is reverting [this commit](https://github.com/pypa/cibuildwheel/commit/6db52297745c0c0c212ce4cd9177bf5b1497b00b).
> Enable Pycln since the artificial limit removed for all Python3 versions.

- cibuildwheel/windows.py
This PR adds a `python3.exe` link pointing to `python.exe` on windows, closes #915.
> Add python3.exe symlink on windows builds.

- .circleci/config.yml
We'll need a better solution to this, but for now, every PR being red is making it hard to work on the project, so this will tide us over.
> Workaround CircleCI timeouts by deselecting tests

- README.md
- cibuildwheel/environment.py
- cibuildwheel/options.py
- cibuildwheel/resources/defaults.toml
- docs/options.md
- unit_test/docker_container_test.py
- unit_test/environment_test.py
- unit_test/options_test.py
This is an initial implementation of what passenv would look like. Some thought into escaping quotes is likely needed?
> feat: support passenv

- docs/data/projects.yml
Psycopg uses cibuildwheel since version 3.0. Thank you very much!
> docs: add psycopg 3 to the projects page

- cibuildwheel/options.py
- cibuildwheel/resources/defaults.toml
- docs/cpp_standards.md
- docs/options.md
- test/test_docker_images.py
- test/utils.py
- unit_test/main_tests/main_options_test.py
- unit_test/option_prepare_test.py
- unit_test/options_toml_test.py
closes #909 
Move the default for all platforms to manylinux2014. This is available for all platforms in `resources/pinned_docker_images.cfg`
> always default to manylinux2014

- README.md
With cibuildwheel v2.3.0 came support for PyPy 3.8.
This PR simply adds it to the table under _[What does it do?](https://github.com/Zuzu-Typ/cibuildwheel/tree/patch-1#what-does-it-do)_
> Add PyPy 3.8 to supported operating systems / Python versions table

- examples/travis-ci-deploy.yml
In https://github.com/pygeos/pygeos, I moved the aarch64 builds to Travis. It appeared that the `pypi` deploy provider uploads only wheels from the `dist` directory, not the `wheelhouse` directory.
> Fix Travis deploy example

- cibuildwheel/windows.py
This [fails our CI occasionally](https://app.travis-ci.com/github/pypa/cibuildwheel/jobs/550840205), but we don't really care about the
occasional file escaping deletion - this is more about hygene than
anything else, so ignore errors on this step.
> Ignore rmtree errors on Windows during cleanup

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Closes #942. macOS and Windows currently do not support setting an environment variable that is not supported in the original pip but in the pinned pip we install.
> fix: environment variable affect initial setup macOS/win

- cibuildwheel/docker_container.py
- cibuildwheel/logger.py
- cibuildwheel/macos.py
- cibuildwheel/projectfiles.py
- cibuildwheel/windows.py
minor fixes to get pycharm not to complain too much:
- spelling when deemed appropriate
- variable name shadowing builtin function
- unused assignment
- invalid doc string
> fix: minor fixes to get pycharm not to complain too much

- cibuildwheel/projectfiles.py
- unit_test/projectfiles_test.py
will close #976
without this, windows can attempt to open this file as Windows-1252
> open setup.py as utf-8 in get_requires_python_str

- cibuildwheel/util.py
- unit_test/wheel_print_test.py
Fixes #734
It uses `kB` unconditionally.
e.g.
```
13 wheels produced in 9 minutes:
spam-0.1.0-cp310-cp310-macosx_10_9_universal2.whl  4 kB
spam-0.1.0-cp310-cp310-macosx_10_9_x86_64.whl      3 kB
spam-0.1.0-cp310-cp310-macosx_11_0_arm64.whl       3 kB
spam-0.1.0-cp36-cp36m-macosx_10_9_x86_64.whl       3 kB
spam-0.1.0-cp37-cp37m-macosx_10_9_x86_64.whl       3 kB
spam-0.1.0-cp38-cp38-macosx_10_9_universal2.whl    4 kB
spam-0.1.0-cp38-cp38-macosx_10_9_x86_64.whl        3 kB
spam-0.1.0-cp38-cp38-macosx_11_0_arm64.whl         3 kB
spam-0.1.0-cp39-cp39-macosx_10_9_universal2.whl    4 kB
spam-0.1.0-cp39-cp39-macosx_10_9_x86_64.whl        3 kB
spam-0.1.0-cp39-cp39-macosx_11_0_arm64.whl         3 kB
spam-0.1.0-pp37-pypy37_pp73-macosx_10_9_x86_64.whl 3 kB …
```
> feat: include size in the final printout

- cibuildwheel/macos.py
It seems `sudo` is not required anymore (at least on GHA), let's see for other providers.
> fix: remove warnings on macOS when installing certificates

- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
Closes #672, uses an implementation like the one in https://github.com/pypa/cibuildwheel/pull/672#issuecomment-878323359
Extracted from #974
It might be easier to review this one on its own. I'll rebase #974 on this one.
> refactor: Use utils.call & utils.shell in macos.py & windows.py

- cibuildwheel/docker_container.py
- cibuildwheel/linux.py
Add `--network=host` to Travis-CI PPC64le runners.
Draft to fix #904
Test in https://github.com/openPMD/openPMD-api/pull/1138
> Travis-CI: Fix Container Network

- README.md
- bin/run_tests.py
- bin/update_virtualenv.py
- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/resources/virtualenv.toml
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/options.md
- docs/setup.md
- noxfile.py
- setup.cfg
- setup.py
- Cache python installations to a user cache folder using platformdirs.
- The build environment is now a virtual environment to allow proper isolation.
- Allows to run tests in parallel.
Specific for macOS:
The python.org installers are still installed globally, only one `{major}.{minor}` is allowed to be installed at a time.
The way this is handled does not change with this PR meaning that there might be a mismatch between the installed python version and the one expected by cibuildwheel.
Given shudoers right are necessary to do the installation, in order for local runs to work, the user still has to install the relevant python versions manually.
Edit by joerick: Fixes #104
> feature: allow local runs on windows/macOS

- README.md
This PR is a one-word change to `README.md`. One sentence uses the en-gb spelling `licence` and the next uses the en-us spelling `license`. I've changed the first sentence to match the second.
> Use consistent spelling for "license" in README.md

- .pre-commit-config.yaml
- cibuildwheel/util.py
Closes #1015 by adding a missing field (`requires_python`) to the printout, making this issue much easier to debug in the future. Using dataclasses to simplify this, though I could not statically force `kw_only=True`/`_: KW_ONLY` (via `sys.version_info` or `TYPE_CHECKING`) into this so mypy keeps us from relying on field order (and this also forces skip to be before build, since you can't add a defaulted field before a required one). Also fixed a mistake where `PRERELEASE_SKIP` was being pulled from a not-yet-defined child, which is confusing. `self.<var>` works just fine for reading it, or `self.__class__.var` works too.
> fix: include Requires-Python info in printout

- cibuildwheel/util.py
Addition of Python 3.10 to the checks exposed this.
> fix: A type alias cannot be final

- azure-pipelines.yml
- examples/azure-pipelines-minimal.yml
Update to the oldest non-deprecated images as vs2017-win2016 is [going away in March](https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/#windows).
Closes #1023
> Update Azure Windows image names

- cibuildwheel/docker_container.py
- noxfile.py
- pyproject.toml
Minor cleanup, and make sure pytest is strict.
> chore: cleanup and harden pytest config

- examples/github-deploy.yml
According to the [documentation](https://docs.github.com/en/actions/learn-github-actions/environment-variables), the variable `GITHUB_REF` which is accessed here via `github.ref` has the value `refs/tags/<tag_name>` for tags. `github.event.ref` just contains `<tag_name>` (as described [here](https://stackoverflow.com/a/59349906)).
An alternative edit is of course 
```yaml
if: github.event_name == 'push' && startsWith(github.event.ref, 'v')
```
> Change github.event.ref to github.ref

- bin/update_pythons.py
Opening as draft waiting for PyPy 7.3.9
This reverts commit a0341ab06432b7fe7325a4d478fa3025feefea19.
> Revert "chore: skip PyPy 3.7 7.3.8 updates"

- .pre-commit-config.yaml
- cibuildwheel/options.py
- pyproject.toml
- unit_test/wheel_print_test.py
Using some stricter (and at least one new in 0.940) setting for mypy.
> fix: minor touchups based on stricter mypy settings

- docs/faq.md
The whole block is indented, though a code block with Python formatting is there.
> Fix a badly-formatted Python block in the docs

- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- test/test_0_basic.py
- test/utils.py
Howdy, this PR contains a simple fix for an issue which I came across when using the `--allow-empty` flag. There is some logic in `cibuildwheel.util.print_new_wheels` which is raising an error if no new wheels were built. 
```
mkdir testproj && cd testproj && touch setup.py
CIBW_BUILD="don't match anything" cibuildwheel --platform=linux --allow-empty
```
<details>
```
_ _       _ _   _       _           _
___|_| |_ _ _|_| |_| |_ _ _| |_ ___ ___| |
|  _| | . | | | | | . | | | |   | -_| -_| |
|___|_|___|___|_|_|___|_____|_|_|___|___|_|
cibuildwheel version 2.4.0
Build options:
platform: 'linux'
architectures: {<Architecture.i686: 'i686'>, <Architecture.x86_64: 'x86_64'>}
build_selector: BuildSelector(skip_config='', build_config="don't match anything", requires_python=None, …
```
> fix: Don't error if no new wheels were built

- README.md
- docs/faq.md
- docs: mention when msvcd140_1.dll is included in cpython
Recently investigated in https://github.com/scipy/oldest-supported-numpy/issues/45.
- docs: mention maturin-action
See https://github.com/pypa/cibuildwheel/issues/1038. Also removing the autowheel mention, as it's not been updated in several years.
> docs: two minor additions

- cibuildwheel/options.py
- cibuildwheel/util.py
- unit_test/build_selector_test.py
fixes #1137 
This is a pretty naive approach to the fix- not sure if maybe the Python prerelease stuff should just move to another layer in the class hierarchy instead, but this makes things work as expected at least...
> ensure tests run on prerelease Pythons

- cibuildwheel/macos.py
When I run on macOS, I get the following error:
```
Traceback (most recent call last):
File "/Users/david/.local/pipx/.cache/fd54e06d50697e7/bin/cibuildwheel", line 8, in <module>
sys.exit(main())
File "/Users/david/.local/pipx/.cache/fd54e06d50697e7/lib/python3.10/site-packages/cibuildwheel/__main__.py", line 128, in main
build_in_directory(args)
File "/Users/david/.local/pipx/.cache/fd54e06d50697e7/lib/python3.10/site-packages/cibuildwheel/__main__.py", line 252, in build_in_directory
cibuildwheel.macos.build(options, tmp_path)
File "/Users/david/.local/pipx/.cache/fd54e06d50697e7/lib/python3.10/site-packages/cibuildwheel/macos.py", line 538, in build
shutil.move(str(repaired_wheel), build_options.output_dir)
File "/opt/homebrew/Cellar/python@3.10/3.10.4/Frameworks/Python.framework/Versi …
```
> fix overwriting wheel on macos

- cibuildwheel/docker_container.py
- cibuildwheel/linux.py
- unit_test/docker_container_test.py
- unit_test/option_prepare_test.py
These changes fix Linux builds on Windows, which don't work in v2.5.0. Most of the changes are replacing `PurePath` with `PurePosixPath`.
As far as I can tell, none of the CI services support Linux containers on their Windows runners, so I could not add a regression test.
> Fix Linux builds on Windows

- README.md
- docs/deliver-to-pypi.md
- docs/setup.md
- examples/github-apple-silicon.yml
- examples/github-deploy.yml
- examples/github-minimal.yml
- examples/github-with-qemu.yml
* updates versions (may be more performant)
* added `with:` into text for copy and documented `config-file`
* explain download unpacking files into `dist/`
> Update GitHub Action examples

- docs/options.md
Fixes #879. Documents the setting a Pip option using CIBW_ENVIRONMENT option, with an example.
> Document use of pip options through environment variables

- .github/dependabot.yml
- docs/faq.md
Ignores no longer needed after April 2022. Dependabot keeps the same style pinning now.
> chore: simpler dependabot

- bin/bump_version.py
> henryiii — Yesterday at 2:38 AM
> Why are there both v2.7.0 and 2.7.0 tags for the last few releases? Dependabot seems to pick different ones for different releases. I just noticed I went from 
> v2.6.0 to 2.7.0, but there's still a proper v2.7.0 that it didn't pick.
> 
> joerick — Today at 2:09 PM
> huh, that's weird. I'm not sure!
> I normally try to keep the prefix v2.7.0, not 2.7.0
> I suspect it's something to do with the github releases link
It was something to do with the Github release link in my release script!
> Fix multiple version tags per release bug in release tooling

- cibuildwheel/macos.py
- test/test_macos_archs.py
- test/utils.py
I've added a warning for users, so they know that it doesn't get tested.
See discussion in #1169 for the reason why.
Fixes #1168, fixes #1169
> Don't attempt to test CPython 3.8 wheels on Apple Silicon.

- docs/options.md
- examples/github-minimal.yml
Just a little typo `manylinux2_24` to `manylinux_2_24`
> DOC: Typo manylinux_2_24

- noxfile.py
- setup.py
We really need to upgrade mkdocs! The old version we are stuck on doesn't support Python 3.10 or the latest Markdown.
Should patch the error seen in #1180 with docs.
> fix(docs): pin things due to the mkdocs pin

- README.md
- azure-pipelines.yml
- docs/setup.md
- examples/azure-pipelines-minimal.yml
- examples/github-apple-silicon.yml
- examples/github-deploy.yml
- examples/github-minimal.yml
- examples/github-with-qemu.yml
Bumps docs and Azure to refer to macos-11 since macos-10.15 is deprecated.
Feel free to close if this isn't the right fix and more is needed, I figured I'd get the ball rolling at least in case it isn't.
> DOC: Bump to non-deprecated image

- .pre-commit-config.yaml
Hi, I'm the author of Pycln...
Pycln v2.0.3 has some issues with Py3.9+ so it's highly recommended to upgrade to v2.0.4 ASAP.
> Upgrading Pycln from v2.0.3 to v2.0.4 (a pre-commit hook)

- cibuildwheel/macos.py
Fixes #1193 
Instead of the suggested `sh`, I used `/bin/sh` as that's how Python's subprocess does it:
https://github.com/python/cpython/blob/a566912049722386478c075b83534fa9f7a1de45/Lib/subprocess.py#L1759-L1765
Successful build log: https://cirrus-ci.com/task/5802864923639808
Link to the CI configuration: https://raw.githubusercontent.com/jack1142/cibuildwheel/macos_arch_x86_64_issue/.cirrus.yml
> Fix Rosetta2 usage for shell commands

- cibuildwheel/options.py
- unit_test/options_toml_test.py
Touches up the config errors, including Python 3.10 style suggestions if a name is close to an existing name. This includes `-` and `_` confusion.
Closes #761.
> fix: add suggestions to the TOML error message

- cibuildwheel/architecture.py
- docs/faq.md
- docs/options.md
- examples/github-apple-silicon.yml
- test/test_macos_archs.py
- test/utils.py
Per discussion in #1204, only build `arm64` on arm64 macOS runners.
Fixes #1204
Relates to #1191
> fix: don't build `universal2` as a default on macOS arm64 runners

- azure-pipelines.yml
Test errors in Azure are all printing KeyError: 'reason', it seems to be an incompatibility between pytest-azurepipelines and pytest-xdist. I've filed a bug here: https://github.com/Azure/pytest-azurepipelines/issues/71
in the meantime, I'll disable this plugin.
> Remove pytest-azurepipelines for now

- docs/data/projects.yml
A great example on how to use cibuildwheel for Pyo3 Rust bindings that uses maturin and how to utilize Github Action caches for performance and auto release.
> Add ril to projects.yml

- cibuildwheel/__main__.py
This fixes https://github.com/pypa/cibuildwheel/issues/1252 by using a similar implementation to the one in build_in_directory
> avoid RecursionError on Windows

- bin/update_docker.py
- cibuildwheel/resources/pinned_docker_images.cfg
- docs/options.md
- test/test_manylinuxXXXX_only.py
A `manylinux_2_28` image now exists for the `s390x` architecture.
> feat: manylinux_2_28_s390x support

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/options.py
- cibuildwheel/resources/defaults.toml
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/options.md
- unit_test/main_tests/main_options_test.py
- unit_test/options_test.py
- unit_test/options_toml_test.py
Addresses https://github.com/pypa/cibuildwheel/issues/1227. Don't have much for tests yet, open to ideas.
> feat: support config-settings

- README.md
Pretty sure this was a mistake - we don't support cross compile ARM macOS on platforms where we don't support macOS.
> docs: only macOS platforms support macOS ARM

- .cirrus.yml
Gives us a little more flex for the Cirrus build. I've set these to the maximum because we already use pytest-timeout to catch stalled tests, so there's little need to be conservative. MacOS ARM and aarch64 linux are currently running at 5 and 20 minutes respectively, so no need to increase their limits.
See https://github.com/pypa/cibuildwheel/runs/8321188914 for an example timeout on Linux x86.
> Increase Cirrus CI timeout

- cibuildwheel/util.py
PyLance doesn't like raw Final (and Tuples hard-code the length if you don't specify it). 
Moved to #1270 to unblock this:
Also moved to raising SystemExit over sys.exit. Doesn't require an import & is just the implementation of `sys.exit` anyway. See [python: raise SystemExit (beginner - intermediate)](https://youtu.be/ZbeSPc5wL0g?list=PLWBKAf81pmOaP9naRiNAqug6EBnkPakvY).
> chore: cleanup types

- cibuildwheel/environment.py
- cibuildwheel/options.py
- cibuildwheel/typing.py
- pyproject.toml
- setup.cfg
- unit_test/options_test.py
Fix #1271.
A (perhaps) temporary fix for #1271, reverting to the previous behaviour of wrapping environment variables with double-quotes, which seems to work in 95% of use cases.
There might be a better approach that handles the last 5% of strange/evil inputs. But for now, this should restore the ability to use single-quotes in values and to reference $PARAMs.
> Revert to previous quoting behaviour for environment values in TOML

- cibuildwheel/__main__.py
- unit_test/main_tests/main_platform_test.py
> Fix win32 identifiers with --only

- cibuildwheel/architecture.py
- unit_test/architecture_test.py
This improves the default arch selection when targeting a different platform.
If you run `cibuildwheel --platform linux --print-build-identifiers` from 64-bit Windows, I'd expect to see the identifiers for 64/32-bit Linux. I noticed this because I ran `cibuildwheel --platform windows --print-build-identifiers` from macOS, and got nothing - I expected the 64/32-bit Windows identifiers. However, this _does_ work if you run macos from linux, or vs. versa, as long as you are on Intel, due to a quirk of the names.
I've just fixed the auto arch discovery to be based on the target platforms's matching architecture. `auto` now uses the target OS instead of the current OS to compute the auto architectures.
(This also happens to be a bit nicer for #1261. It also should be _much_ nicer when using …
> fix: better cross-platform auto archs

- bin/inspect_all_known_projects.py
- bin/run_example_ci_configs.py
- bin/update_pythons.py
- cibuildwheel/__main__.py
- cibuildwheel/bashlex_eval.py
- cibuildwheel/functools_cached_property_38.py
- cibuildwheel/linux.py
- cibuildwheel/logger.py
- cibuildwheel/macos.py
- cibuildwheel/oci_container.py
- cibuildwheel/options.py
- cibuildwheel/windows.py
- pyproject.toml
- setup.py
- test/test_dependency_versions.py
- test/utils.py
- unit_test/main_tests/conftest.py
- unit_test/main_tests/main_options_test.py
- unit_test/option_prepare_test.py
- chore: drop [all] extra
This could be a hindrance to moving to static configuration, and isn't that useful or that great of an idea (the more deps in one environment, the more fragile it is). Let's just remove it.
- chore(bin): remove ghapi requirement
We already require PyGitHub, and that's fully typed, so let's just use that. Also cleaned up this script (not sure if we really need it, but let's keep it nice as long as we have it).
- chore: cleaner exception tracebacks
I wrote a flake8 check and description for this here: https://github.com/henryiii/flake8-errmsg. I'm not adding the check at the moment, just cleaning up the existing exceptions. I improved the text of a few exceptions, too. I think we shouldn't throw raw `Exception`s, but should at least do `RuntimeError`, but I didn't …
> chore: nicer tracebacks and dev improvements

- docs/deliver-to-pypi.md
- docs/faq.md
Fix #1251
I took the opportunity of tidying up the tips and tricks page at the same time - titles should be more consistent now.
> Tidy up the Tips and Tricks page and add information about Homebrew deps

- cibuildwheel/architecture.py
- cibuildwheel/typing.py
I was working on my lectures for this week (which are [over static typing](https://henryiii.github.io/se-for-sci/content/week5/typing)), and remembered we can clean this up. It doesn't even need a typing extensions bump; 4.1 is sufficient.
> chore: clean up a little typing

- .cirrus.yml
- cibuildwheel/macos.py
- test/conftest.py
- test/test_macos_archs.py
- unit_test/conftest.py
Per discussion in https://github.com/pypa/cibuildwheel/pull/1169, the default installer used for cp38 is an Intel installer. It makes sense to skip testing arm64 wheels in this case.
However, if the user choose to manually install the universal2 CPython version (c.f. https://github.com/pypa/cibuildwheel/issues/1278#issuecomment-1256943685), then, tests shall be run on arm64.
This allows users that either target 11.0+ on intel, universal2 or only build for arm64 to get the arm64 wheel tested on AppleSilicon.
I'm not a fan of the way I added the test here but there's a test. Maybe the test suite should be updated to run fully with both installers ?
> feature: allow testing cp38-macosx_arm64 wheel

- cibuildwheel/linux.py
- test/test_linux_python.py
See https://github.com/pypa/cibuildwheel/issues/1187#issuecomment-1191222248
Close #1187
> chore: better error message when python is missing in an OCI image

- cibuildwheel/linux.py
This was included in pip a while ago (22.1, IIRC?) but we haven't added it yet.
> fix: hide root pip warning on Linux

- .gitlab-ci.yml
- README.md
- docs/data/projects.yml
- examples/gitlab-minimal.yml
- examples/gitlab-with-qemu.yml
> Update GitLab support

- .circleci/config.yml
- README.md
- docs/data/projects.yml
- examples/circleci-minimal.yml
- add note in docs that pyzmq uses both github and circleci, and that it includes native linux arm builds on circle
- add linux-aarch64-wheels job to circleci-minimal example
closes #1241
> docs for native arm building on circleci

- cibuildwheel/macos.py
- test/test_macos_archs.py
When `MACOSX_DEPLOYMENT_TARGET` is not set by the user, cibuildwheel always defaults to `10.9`. This leads to a warning when building arm64 wheels.
This commit removes the warning by setting the default to `11.0` for arm64 builds.
Reported in https://github.com/pypa/cibuildwheel/pull/1300#issuecomment-1278396244
> fix: warning when building macOS arm64 wheels

- docs/faq.md
> Add FAQ entry about Python 3.8 native arm64 workaround

- cibuildwheel/oci_container.py
Fix #1161 - making stdout line-buffered.
I can't think how to add a unit test for this because capfd keeps stdout and stderr separately. But on my machine, this-
```
python -m test.test_projects test.test_0_basic.basic_project /tmp/basic_project
(cd /tmp/basic_project && CIBW_BEFORE_BUILD="python -uc 'import sys, time; print(1, file=sys.stdout); time.sleep(0.1); print(2, file=sys.stderr)'" cibuildwheel --platform linux)
```
Prints 
```
2
1
```
before this PR and ...
```
1
2
```
after.
> Fix #1161 - stdout is line-buffered during command execution

- cibuildwheel/resources/defaults.toml
- docs/faq.md
- docs/options.md
- unit_test/main_tests/main_options_test.py
Minor PR to make a small tweak to cibuildwheels default mac wheel repair command. Instead of having to call `delocate-listdeps` separately, `delocate-wheel` can be invoked with a verbose flag, and this should print very similar information to the previous extra command.
> Tweak default mac repair cmd: use delocate-wheel verbose flag instead of extra listdeps command

- .github/workflows/test.yml
- .pre-commit-config.yaml
- CI.md
- action.yml
- setup.cfg
With 3.11.0 available in roughly a couple weeks, let's start testing as draft.
I will update this once 3.11 reaches GA.
> chore: test with Python 3.11

- cibuildwheel/linux.py
- test/test_0_basic.py
Fixing this, try 2. Closes #1310.
> fix: hide root pip warning and upgrade check

- action.yml
Fixes #1338 by using the native GHA shell (powershell) on Windows. Using bash changes the path unexpectedly.
You can see it working for existing projects at https://github.com/pybind/scikit_build_example/actions/runs/3524040183/jobs/5908931400. "pipx run cibuildwheel" was verified to work with meson-python independently.
> fix: action using powershell on Windows

- .github/workflows/test.yml
Just noticed that this step takes 10+ minutes - probably we can get away without it - let's try
> Faster Github linux CI by removing 'apt-get upgrade -y' from podman install

- .github/workflows/update-dependencies.yml
ubuntu-latest / 22.04 does not have python 3.6, use ubuntu-20.04 instead.
> fix(ci): use ubuntu-20.04 for update workfow

- docs/faq.md
- docs/options.md
> Suggest running abi3audit in docs

- .github/workflows/test.yml
I think the old one might be getting phased out.
> ci: move to ubuntu 20

- cibuildwheel/windows.py
If you don't skip the tests, the final copy of the wheels is skipped after printing the warning message when cross-compiling for Win ARM!
IMO, these should be refactored to one function per action (prepare, build, repair, test, finalize, something like that) instead of massive, all-in-one function that's hard to track; it would make bugs like this harder to make. Blocks should not be more than a few lines.
> fix: not skipping the tests stops the copy (Windows ARM)

- appveyor.yml
- examples/appveyor-minimal.yml
use normal AppVeyor macOS image i.e. catalina (10.15) per https://github.com/pypa/cibuildwheel/pull/1372#issuecomment-1369773672 comment.
towards #1372 & #1381 
Created a PR cherry-picking @henryiii commits (I think this might be cleaner looking at commit history depending how it would be merged).
Order for merging would be this PR then #1381 and then #1372
> ci: use normal AppVeyor macOS image

- docs/data/projects.yml
Some people will be interested in additional examples for Cirrus CI and how to include third party libraries using MSYS2 for Windows.
For Cirrus, use a slightly different technique than scipy to show another way to get wheels out of it.
> Examples: Updated info for pillow_heif

- .pre-commit-config.yaml
- bin/bump_version.py
- bin/update_pythons.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/oci_container.py
- cibuildwheel/options.py
- cibuildwheel/projectfiles.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- pyproject.toml
- setup.cfg
- test/test_cpp_standards.py
- test/test_environment.py
- test/test_pure_wheel.py
- unit_test/conftest.py
- unit_test/main_tests/conftest.py
- unit_test/main_tests/main_options_test.py
- unit_test/main_tests/main_platform_test.py
- unit_test/main_tests/main_requires_python_test.py
- unit_test/option_prepare_test.py
- unit_test/options_test.py
- unit_test/options_toml_test.py
- unit_test/utils_test.py
- unit_test/wheel_print_test.py
- chore: use ruff
- chore: use ruff (manual changes)
Is 10-100x faster (written in Rust), combines flake8 and lots of plugins, pyupgrade, isort, pygrep, yesqa, and some of flake8 (so pre-commit setup is faster - also just a simple binary, I think). And pyproject.toml configured! Also can do auto-fixes for quite a few errors.Ran into a few minor bugs that have already been fixed upstream. Used by Pandas, FastAPI, SciPy, Build, etc. More pre-commit friendly, since we don't have breakage due to plugins not being pinned (because they are all built-in, so there's only the one pre-commit ref).
Suggested in https://github.com/pypa/cibuildwheel/pull/1399#issuecomment-1397340132.
> chore: use Ruff

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- unit_test/main_tests/main_options_test.py
Closes #1429. Only "build" backend supported config options, since pip uses a different name (with an s).
> fix: pip config options were broken

- docs/options.md
I wouldn't normally document OS features/quirks in our documentation, but here, it wasn't the user that changed the working dir to another drive, it was cibuildwheel, so it seems fair to note some gotchas.
Fixes #1448
> add warning about `cd /d` in test-command

- test/test_windows.py
Quick fix for https://github.com/charliermarsh/ruff/pull/3876 - also, besides consistency, I like this a bit better, because it's easy to assume that envvar's are case sensitive when you see them in camel case. I was confused by that once on Windows (I had a nice idea that was broken by them not being case sensitive on just this one OS).
> tests: use uppercase envvar on Windows

- cibuildwheel/__main__.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/typing.py
- cibuildwheel/windows.py
Use structural typing for the return value of get_python_configurations so that we don't have to specify a union of all possible `PythonConfiguration` types.
This makes it slightly more convenient to add a new platform.
> chore: add structurally typed GenericPythonConfiguration

- cibuildwheel/__main__.py
build_in_directory was ~140 lines long which is a bit long for my taste. It also has a bunch of nested if statements which I don't prefer. The first ~60 lines are computing the platform, so I factored those out into helper methods which have clearer intent and less indentation.
> chore: factor out _compute_platform from build_in_directory

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/options.py
- cibuildwheel/resources/defaults.toml
- cibuildwheel/util.py
- cibuildwheel/windows.py
Instead of using pip as the default, set it to default. This way each platform can choose independently what to do as the default behavior.
This is intended as part of adding Pyodide support #1456. Pyodide cannot use pip as the build frontend. It always uses a modified pypa/build. So if the build_frontend is explicitly set to pip we want to raise an error. But if it's unset, then we should be able to tell and just do what we want.
> Set the default build_frontend to be "default" (which is still "pip")

- cibuildwheel/windows.py
This is the same fix as #1129 but for Windows this time.
> fix: overwriting wheel on windows shouldn't break

- .pre-commit-config.yaml
- cibuildwheel/__main__.py
- pyproject.toml
- setup.py
Adding a bit of cleanup from looking at #1297 again. Drops the unmaintained `[mypy]` extra.
- chore: clean up mypy a little bit
- chore: clean up pylint/black a bit
> chore: minor cleanup

- cibuildwheel/architecture.py
- cibuildwheel/logger.py
I use VS Code and it doesn't like these unspecified Final types, so I'm specifying fully to get rid of the red squigglies.
> Fix a few types to keep pyright happy

- bin/update_virtualenv.py
I'd like not to drop 3.6 right away (& possibly up-to centos 7 EOL or OpenSSL 1.1.1 EOL) as it is still used in around 15% of wheel builds (on linux at least).
> chore: update to virtualenv<20.22.0

- .github/workflows/release.yml
Basically copying https://github.com/scikit-build/scikit-build-core/pull/306
And following https://docs.pypi.org/trusted-publishers/adding-a-publisher/
> Use PyPI Trusted Publisher for releases

- cibuildwheel/linux.py
- cibuildwheel/oci_container.py
- cibuildwheel/options.py
- cibuildwheel/util.py
- docs/options.md
- test/test_container_engine.py
- test/utils.py
- unit_test/oci_container_test.py
- unit_test/options_test.py
Fix #1384
Adds the ability to give additional command line arguments to the container engine (docker or podman). These are supplied inside the existing CIBW_CONTAINER_ENGINE option in a backward-compatible format so we don't increase the options surface area, and because, in theory at least, these options could vary in future depending on the container engine used.
> Add create_args suboption to CIBW_CONTAINER_ENGINE

- docs/options.md
This is a minor docs fix. It looks like it was originally a copy-paste-modify but with the modify stage missing.
Whilst I am here, thanks very much for such a useful project.
> Minor docs fix

- .travis.yml
Travis for windows has been failing for a few days with this error:
```
$ powershell "md C:\temp\certs; CertUtil -generateSSTFromWU C:\temp\certs\RootStore.sst; Get-ChildItem -Path C:\\temp\certs\Rootstore.sst | Import-Certificate -CertStoreLocation Cert:\\LocalMachine\\Root\\ | out-null"
Directory: C:\temp
Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----         6/6/2023   9:53 AM                certs                                                                 
The data is invalid. 0x8007000d (WIN32: 13 ERROR_INVALID_DATA) -- authrootstl.cab
CertUtil: -generateSSTFromWU command FAILED: …
```
> Fix Travis Windows builds

- .github/workflows/update-major-minor-tag.yml
This PR will automatically push an updated vMAJOR.MINOR tag for cibuildwheel. e.g. the tag `v2.14` would point to version `v2.14.2`, until `v2.14.3` comes out.
It's implemented using a fork of https://github.com/actions/publish-action , https://github.com/joerick/update-vX.Y-tag-action
Context from discord:
@henryiii:
> I've resisted moving vX tags since cibuildwheel adds and removes platforms in minor releases, but what do you think about a moving vX.Y tag to reduce dependabot chatter on patch releases?
> Dependabot won't update to a different number of .'s since April 2022, so it would be entirely opt-in.
> Add workflow that updates a vX.Y tag on release

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
Taken by clicking the link in #1504.
> fix: allow access to {wheel} in more places

- docs/deliver-to-pypi.md
- examples/github-deploy.yml
Close #1522. Simplified the example a bit.
> docs: use trusted publisher for GHA docs/example

- .cirrus.yml
- .github/workflows/test.yml
- azure-pipelines.yml
Saves a bit of pointless CI time. Jenkins and Circle don't support it.
> Ignore docs changes on Azure Pipelines and CirrusCI

- docs/data/projects.yml
We've moved to github actions and added windows support. Also add a note about our use of the stable ABI which may be the most interesting part of our config.
Replaces #1570
> Update Tornado's entry in projects.yml

- cibuildwheel/options.py
- unit_test/main_tests/main_platform_test.py
> fix: --only shouldn't require prerelease pythons setting

- docs/options.md
Update setuptools link to new URL, and add `pyproject.toml` as a source file (as already done in the example).
> Doc: Update info for CIBW_TEST_EXTRAS

- README.md
- docs/deliver-to-pypi.md
- docs/setup.md
- examples/github-apple-silicon.yml
- examples/github-deploy.yml
- examples/github-minimal.yml
- examples/github-with-qemu.yml
> chore: use actions/checkout@4 everywhere

- .gitattributes
- cibuildwheel/_compat/tomllib.py
- cibuildwheel/_compat/typing.py
- pyproject.toml
A couple of minor additions.
- chore: Ruff ignore for `_compat`
- chore: add `.gitattributes`
- Better EoL handling if someone doesn't have git set up correctly
- Better contextual diffs for Python and markdown
- Ignore binary-like matches in svgs when grepping
> chore: minor additions

- .readthedocs.yml
As spotted in #1617, this is now required.
> Update RtD config to include mandatory build.os option

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/oci_container.py
- cibuildwheel/options.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- docs/options.md
- test/test_build_frontend_args.py
- unit_test/main_tests/main_options_test.py
- unit_test/options_test.py
Fixes #1580.
Adds the ability to pass extra arguments to the build frontend using an option like `CIBW_BUILD_FRONTEND=pip; args: --no-build-isolation`. The mini-syntax is the same as CIBW_CONTAINER_ENGINE. 
I liked this approach because it adds extra flexibility to the existing CIBW_BUILD_FRONTEND option in a backward-compatible way. Also, options are always going to be different between pip and build, so it makes sense to nest those within this option - if you change the build frontend, you have to change the args too.
> Add the ability to pass extra flags to a build frontend through CIBW_BUILD_FRONTEND

- cibuildwheel/oci_container.py
- docs/options.md
- unit_test/oci_container_test.py
Support for reproducible builds: https://reproducible-builds.org/docs/source-date-epoch/
> feature: Automatically pass SOURCE_DATE_EPOCH to Linux containers

- cibuildwheel/projectfiles.py
- unit_test/projectfiles_test.py
Fixes #1611. We could slide down a slippery slope here, but this one is common and simple (vs. supporting `**kwargs` or something like that). And the code will look a lot better once we drop Python 3.9 from our runners in a few years.
> fix(setup.py): look inside if name == main block

- .github/workflows/test.yml
- cibuildwheel/linux.py
- cibuildwheel/oci_container.py
- test/conftest.py
- unit_test/oci_container_test.py
- unit_test/option_prepare_test.py
The `linux32` command is always used for linux i686.
This makes cross building from macOS arm64 impossible at the moment (might depend on docker configuration).
This PR proposes to check the architecture seen inside the container before using (or not) the `linux32` command.
> fix: do not use `linux32` when unnecessary

- bin/generate_schema.py
- cibuildwheel/resources/cibuildwheel.schema.json
- unit_test/validate_schema_test.py
Small touchup to schema. Overrides needs select and at least one more item.
> fix: ensure 2+ items in each override in schema

- cibuildwheel/linux.py
This will allow dropping some EOL (and maybe some none EOL) python interpreters in manylinux images which would allow to reduce its size (faster for a vast majority of user, a small slow-down for users of those interpreters).
Updates to keep tests times down are not here yet, this is just to get things started.
> feat: use manylinux-interpreters tool if present

- bin/generate_schema.py
- cibuildwheel/resources/cibuildwheel.schema.json
Refactoring this to be a bit simpler and reduce the number of lines in the schema by a lot (around 800). The only loss is the custom titles for the OS-specific variants, but I think that's fine.
> refactor: use refs instead of copies

- cibuildwheel/oci_container.py
- docs/options.md
closes #1320. With this flag enabled, the containers of local (failing) builds can be debugged afterwards.
> feat: `CIBW_DEBUG_KEEP_CONTAINER`: debug container after build

- bin/generate_schema.py
- cibuildwheel/resources/cibuildwheel.schema.json
- noxfile.py
Fixing a small bug discovered when running this via SchemaStore's tests that fastjsonschema apparently doesn't care about (extra list). Also have a way to specify the full schema (with tool.cibuildwheel) so that cibuildwheel.toml/.cibuildwheel.toml can be checked. (Currently not sure how to have a subschema that doesn't have a file also, but this will at least move cibuildwheel forward, because we do).
https://github.com/SchemaStore/schemastore/pull/3287
> fix(schema): small bug + prepare for SchemaStore

- .pre-commit-config.yaml
- bin/run_example_ci_configs.py
- cibuildwheel/_compat/typing.py
- cibuildwheel/oci_container.py
- pyproject.toml
Some small updates, preparing for ruff-format.
> fix: minor ruff updates

- .pre-commit-config.yaml
- bin/update_pythons.py
- cibuildwheel/util.py
- pyproject.toml
- test/test_before_test.py
- test/test_cpp_standards.py
- test/test_dependency_versions.py
- test/test_emulation.py
- test/test_pep518.py
- test/test_pure_wheel.py
- test/test_same_wheel.py
- test/test_subdir_package.py
- test/test_testing.py
Moving to ruff-fmt. Faster, drops a dependency, less config, and formatting is a bit better.
See https://github.com/scientific-python/cookie/pull/299 and https://astral.sh/blog/the-ruff-formatter.
> chore: move to ruff-format

- docs/data/projects.yml
This pull request proposes the addition of our package, werpy, to the list of working examples in the cibuildwheel documentation. 
Werpy is a fast, lightweight Python package for calculating and analyzing Word Error Rate (WER) between two sets of text. 
This package demonstrates a successful use case of cibuildwheel for building and distributing Python packages with C extensions and provides a good use case for others to view.
> Update projects.yml to add new repo for working examples

- cibuildwheel/macos.py
- cibuildwheel/windows.py
- docs/faq.md
We found (re: https://github.com/python-pillow/Pillow/pull/7552#pullrequestreview-1732529361) we needed to add quotes to `CIBW_TEST_SKIP: "*-macosx_arm64"` to silence the warnings.
And this matches the recommendation in docs: https://cibuildwheel.readthedocs.io/en/stable/options/#test-skip
> Use quotes when silencing warning

- docs/faq.md
This was a historic mistake in the `setuptools`' docs that many projects copied. But `wheel` is already a dependency injected by `setuptools` when needed. So let's not suggest people to depend on it when producing sdists.
> Stop suggesting adding `wheel` to `pyproject.toml`

- docs/options.md
Ref #1666. The CIBW_ENVIRONMENT and CIBW_ENVIRONMENT_PASS options also affect the test phase, which wasn't clear.
Also, there are some environment variables that are overridden as part of cibuildwheel's operation. Good to note these so users are aware.
> docs: Address some confusion around the CIBW_ENVIRONMENT option.

- docs/deliver-to-pypi.md
- docs/setup.md
- examples/github-apple-silicon.yml
- examples/github-deploy.yml
- examples/github-minimal.yml
- examples/github-with-qemu.yml
See discussion: https://github.com/pypa/cibuildwheel/issues/1699
> docs: update examples for v4 of `upload-artifact` and `download-artifact` actions

- .github/workflows/release.yml
- .github/workflows/test.yml
Supersedes (and closes https://github.com/pypa/cibuildwheel/pull/1709)
> Upgrade artifact actions in workflows to v4

- bin/generate_schema.py
- cibuildwheel/oci_container.py
- cibuildwheel/options.py
- cibuildwheel/resources/cibuildwheel.schema.json
- cibuildwheel/util.py
- docs/extra.css
- docs/faq.md
- docs/options.md
- unit_test/oci_container_test.py
- unit_test/options_test.py
> feat: Adds disable_host_mount suboption to container-engine

- cibuildwheel/__main__.py
- test/test_from_sdist.py
This patch changes the working directory from the temp to the project when building sdist package. This resolves issues with relative paths in configuration files.
Resolves #1683
> Edit path when building sdist package

- action.yml
Fixes compatibility with PowerShell 7.3 on Windows through GitHub Actions when one of the options for cibuildwheel is empty.
I'm not sure how you want to go about this but I believe this should solve the issue with the migration of GHA to PowerShell 7.4 that is happening now.
Fixes: https://github.com/pypa/cibuildwheel/issues/1740
> Add support for PowerShell 7.3 in GHA

- action.yml
Takes an extra second or two, plus it could interfere with the environment a bit if someone activates the same version of Python. But not too bad.
> fix: download pipx for action, allow support for M1

- cibuildwheel/macos.py
- test/test_macos_archs.py
pip cannot install wheels with different architecture into the same venv directory. (See https://github.com/pypa/cibuildwheel/issues/1746#issuecomment-1920164503)
Downstream test:
Before this PR: failed [log](https://github.com/tongzhugroup/mddatasetbuilder/actions/runs/7733603508/job/21086015132)
After this PR: pass [log](https://github.com/tongzhugroup/mddatasetbuilder/actions/runs/7748040866/job/21129838429)
> test macos-x86_64 and arm64 in different venv dir

- .github/workflows/test.yml
- action.yml
Only pass arguments that were set by the action to cibuildwheel.
Also add tests for action `only` & `config-file` arguments.
This allows to remove the workaround for `pwsh` update in https://github.com/pypa/cibuildwheel/pull/1741.
IMHO, this also brings some clarity when looking at the command-line that's being run:
e.g. https://github.com/pypa/cibuildwheel/actions/runs/7853848516/job/21433975640#step:8:64
```
Run if ($PSNativeCommandArgumentPassing) {
```
will now produce:
```
Run & "C:\hostedtoolcache\windows\Python\3.12.1\x64\python.exe" -m pipx run --spec "D:\a\cibuildwheel\cibuildwheel\./" cibuildwheel "sample_proj" --output-dir "wheelhouse"
```
> chore(action): update cibuildwheel arguments passing

- bin/dev_run_test
- cibuildwheel/__main__.py
- docs/options.md
- docs/setup.md
- unit_test/main_tests/main_platform_test.py
Historically, we required `--platform` when running cibuildwheel outside of CI, because cibuildwheel would attempt to globally install Python interpreters and some packages.
That was fixed in https://github.com/pypa/cibuildwheel/pull/974 a couple of years ago. As a result, there's no reason to require --platform these days, the `auto` behaviour is perfectly fine for dev machines.
It also makes running tests locally simpler, one can just do `pytest test/test_0_basic.py` (or `nox -s tests -- test/test_0_basic.py`) and not have to worry about setting CIBW_PLATFORM most of the time.
> Don't require `--platform` when running on a development machine

- .circleci/config.yml
- examples/circleci-minimal.yml
As described [here](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177), the Linux image used in the example has been deprecated, and the CircleCI example will stop working soon unless it gets updated.
> Replace deprecated runner in CircleCI example

- bin/generate_schema.py
- cibuildwheel/options.py
- cibuildwheel/resources/cibuildwheel.schema.json
- docs/options.md
- unit_test/options_test.py
- unit_test/options_toml_test.py
- unit_test/validate_schema_test.py
This implements my follow-up suggestion in #1716, modified. Example:
```toml
[tool.cibuildwheel]
environment = {FOO="BAR", "HAM"="EGGS"}
test-command = ["pyproject"]
[[tool.cibuildwheel.overrides]]
select = "cp311*"
inherit.test-command = "append"
inherit.environment = "append"
test-command = ["pyproject-override"]
environment = {FOO="BAZ", "PYTHON"="MONTY"}
```
This example will provide the command `["pyproject", "pyproject-override"]` on
Python 3.11, and will have `environment = {FOO="BAZ", "PYTHON"="MONTY", "HAM"="EGGS"}`. Both `"append"` and `"prepend"` are supported (`"none"` is the default). You can even chain them to both append and prepend in matching override blocks.
> feat: add inherit to override

- action.yml
If #1743 is just meant to be temporary while waiting on https://github.com/actions/runner-images/issues/9256, then that's ok. 
However, if we need this in the long run, I'd rather not change the worker default environment. It's not necessarily an issue for github-hosted workers which are ephemeral but it could became an issue for self-hosted.
> chore(action): do not use pipx

- docs/data/projects.yml
[`pedalboard`](https://github.com/spotify/pedalboard) is a Python library that makes it easy, fast, and intuitive to work with audio data in Python.
Under the hood, it wraps [the JUCE framework](https://github.com/juce-framework/JUCE/) to allow extremely high-speed, thread-safe audio processing - and uses `cibuildwheel` to distribute effortlessly to nearly any platform: macOS, Windows, manylinux, musllinux, arm64, x86, Python 3.6-3.12, etc; with just a `pip install`. (The project wouldn't have been possible without cibuildwheel; thanks @henryiii!)
> Add `pedalboard` to projects.yml.

- cibuildwheel/macos.py
Fixes https://github.com/pypa/cibuildwheel/issues/1767
> Set SYSTEM_VERSION_COMPAT=0 during pip install on macos

- bin/update_docker.py
Reverts the workaround in #1783
> Remove manylinux1 docker pin

- .cirrus.yml
- examples/cirrus-ci-intel-mac.yml
- examples/cirrus-ci-minimal.yml
- test/test_from_sdist.py
Noticed a few cirrus issues on the `main` build. Would like to get these fixed before the next release.
> CirrusCI fixes

- README.md
- docs/changelog.md
- docs/faq.md
- docs/options.md
- setup.cfg
Fixes #1688.
Will merge immediately before next release.
Other tasks to do when merging:
> Docs domain change to cibuildwheel.pypa.io

- bin/generate_schema.py
- cibuildwheel/resources/cibuildwheel.schema.json
Quick fix based on https://github.com/SchemaStore/schemastore/pull/3635. Using standard `$refs` now. Also reordered a bit to match what schema store's linters do.
> fix(schema): use $refs instead of defines

- README.md
- docs/setup.md
The docs currently refer to actions/setup-python@v3
This updates it to the latest version, v5 - https://github.com/actions/setup-python/releases
> Updated actions/setup-python in docs

- docs/faq.md
After 3 years, I finally contributed to delocate with [PR](https://github.com/matthew-brett/delocate/pull/198) is adding validation of platform tag against real requirements. 
As many users open issues in this repository even when should in some other package, I think is worth to at least opening PR for better visibility. 
This PR should not be merged before the next delocate release.
> Add information about new delocate error "Library dependencies do not satisfy target MacOS" 

- cibuildwheel/macos.py
- cibuildwheel/windows.py
- test/test_dependency_versions.py
When building a project that has a `pyproject.toml`, constraints are not respected when building with the `pip` frontend.
This commit fixes this by using the same tricks as for the `build` frontend.
> fix: respect constraints when building with pip

- cibuildwheel/resources/constraints-python36.txt
- cibuildwheel/util.py
- test/test_abi_variants.py
Since https://github.com/pypa/cibuildwheel/commit/9879937c6374b3fa6c29a578be3170751d61b80b, setuptools & wheel are not pinned/installed anymore.
We should not pre-seed the virtual environment with those either.
> fix: do not pre-seed setuptools / wheel in virtual environment

- cibuildwheel/options.py
- cibuildwheel/resources/defaults.toml
- cibuildwheel/resources/pinned_docker_images.cfg
- docs/faq.md
- docs/options.md
- test/utils.py
- unit_test/option_prepare_test.py
Statistics for musl (mostly Alpine but also some OpenWRT)
BigQuery sql query:
```sql
SELECT
details.distro.name as distro_name,
details.distro.version as distro_version,
details.distro.libc.lib as libc_name,
details.distro.libc.version as libc_version,
COUNT(*) as download_count,
FROM `bigquery-public-data.pypi.file_downloads`
WHERE timestamp BETWEEN TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL -6 DAY) AND TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL -1 DAY)
AND details.installer.name = "pip"
AND details.system.name = "Linux"
AND file.filename LIKE "%musllinux%"
AND (details.distro.libc.lib IS NULL OR details.distro.libc.lib != "glibc")
GROUP BY
distro_name, distro_version, libc_name, libc_version
ORDER BY
download_count DESC
LIMIT 100
```
Once …
> feat: move default `musllinux` build to `musllinux_1_2`

- .readthedocs.yml
- README.md
- docs/faq.md
Two related changes:
- **docs: add FAQ entry on Rust**
- **ci: make readthedocs faster**
Before, on readthedocs:
After:
> docs: rust

- .readthedocs.yml
- mkdocs.yml
- noxfile.py
The options page is broken, and mkdocs "helpfully" hides errors and just puts them on the output page!
MkDocs macros breaks if the Python environment isn't activated. ¯\_(ツ)_/¯
> docs: fix options page

- .readthedocs.yml
- README.md
- bin/generate_schema.py
- bin/projects.py
- docs/changelog.md
- docs/data/projects.yml
- docs/main.py
- docs/working-examples.md
- noxfile.py
Modernize, use PEP 723 more, faster. Fix redirects. Fix building docs from an unsourced venv. Fix typo in changelog.
> chore: more modern nox

- test/test_macos_archs.py
- test/utils.py
When running on arm64, macOS reports machine as `arm64` and Windows as `ARM64`. We need to override this to `aarch64` when running linux tests.
> fix(tests): linux tests from macOS/Windows arm64

- bin/update_virtualenv.py
- cibuildwheel/macos.py
- cibuildwheel/resources/virtualenv.toml
- cibuildwheel/util.py
- cibuildwheel/windows.py
- test/test_dependency_versions.py
virtualenv has been pinned to 20.21.1 in order to be able to create python 3.6 venvs.
This commit allows to pin virtualenv for given versions of pythons which in turns re-allows updates as a default.
> chore: un-pin virtualenv update

- test/test_before_build.py
- test/test_before_test.py
This would help reduce the amount of specific code for pyodide in #1456
> chore(tests): do not use hard-coded paths in tests

- test/test_abi_variants.py
- test/test_before_all.py
- test/test_before_build.py
- test/test_build_frontend_args.py
- test/test_build_skip.py
- test/test_container_engine.py
- test/test_cpp_standards.py
- test/test_environment.py
- test/test_from_sdist.py
- test/test_macos_archs.py
- test/test_musllinux_X_Y_only.py
- test/test_subdir_package.py
- test/test_testing.py
- test/test_wheel_tag.py
- test/test_windows.py
- test/utils.py
Seeing the many tests that were changed in #1456 to move from one python version to another, we might want a helper for that so that we can do the change in a single location.
Using a single python version is extended to the following tests in order to reduce CI load:
- test_before_all.py
- test_before_build.py:test_cwd
- test_build_skip.py (by updating the skip pattern for the build)
- test_cpp_standards.py (even though "python version independent" wasn't quite true for PyPy at some point)
- test_environment.py
- test_musllinux_X_Y_only.py
- test_testing.py: test_extras_require
There are also 1 other commits to reduce the load on CI for [test_abi3](https://github.com/pypa/cibuildwheel/pull/1835/commits/29e56b5344a0d7b9ca1882db7ceee0b5fba58da3).
> chore: rework single python tests

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
While reviewing #1456, the way that the test virtual environment was seeded was bugging me.
We're not really enforcing anything other than "do not download something new" but, it did not prevent using some version already in virtualenv cache (unlikely in CI but still possible, more likely for local builds).
This PR ensures that the test virtual environment gets seeded with determinism w.r.t. pip, setuptools & wheel versions.
> chore: better determinism for the test virtual environment

- .github/workflows/test.yml
- test/conftest.py
- test/test_emulation.py
- test/utils.py
Just to get a faster GHA overall result.
This also allows to run selected architecture locally if need be.
> chore(ci): split emulation tests per architecture

- cibuildwheel/windows.py
This shouldn't be needed anymore.
> chore: remove pip <21.3 workaround

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/pyodide.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- test/test_testing.py
Include the `VIRTUAL_ENV` variable when running "in" a virtualenv. This will be useful when we start trying out uv.
> fix: include VIRTUAL_ENV variable

- cibuildwheel/macos.py
- cibuildwheel/pyodide.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
In cases where the output_dir does not already exist, the attempt to move the tested wheel to the output_dir actually ends up creating a file named `output_dir` rather than `outputdir/wheelname.whl`
This leads to the build process failing on macos and windows if the directory does not exist, or is removed as part of a before-build clean.
This PR updates the handling of the final wheels to:
1. explicitly resolve the output directory path
2. explicitly create the output directory if it does not already exist
3. then move the wheel file
It also cleans up the handling of errors by making use of built in pathlib.Path functionality rather than with contextlib.suppress
It has been tested in Github actions CI against a specific project & commit which provided a consistent, reproducible error …
> Handle case where output_dir does not already exist on macos & windows

- cibuildwheel/resources/build-platforms.toml
- cibuildwheel/resources/constraints-pyodide312.txt
- cibuildwheel/resources/constraints-python310.txt
- cibuildwheel/resources/constraints-python311.txt
- cibuildwheel/resources/constraints-python312.txt
- cibuildwheel/resources/constraints-python313.txt
- cibuildwheel/resources/constraints-python38.txt
- cibuildwheel/resources/constraints-python39.txt
- cibuildwheel/resources/constraints.txt
Bumping for pyodide 0.26.1, which contains some important fixes.
We should probably automate this. You can get the emscripten version from pyodide build, not sure if there's a better way.
> chore: bump pyodide

- cibuildwheel/util.py
Using  `log.notice` result in many unwanted annotations, at least in GitHub Actions.
If we want to print some information about a specific file being moved, it shall be done by the caller - or adding an option to the function - and use `print`.
> fix: `util.move_file` shall not use `log.notice`

- bin/generate_schema.py
- docs/contributing.md
Noticed a minor warning when running for SchemaStore in https://github.com/SchemaStore/schemastore/pull/3850.
> fix: warning in generate schema script

- action.yml
- cibuildwheel/pyodide.py
Currently we are not always getting a version of Python that supports the pyodide platform in the action. This makes sure we do that.
Edit: This is not actually correct, the problem with or without this is cibuildwheel is looking for and can't find 3.12, even though it is running on 3.12. Running a setup-python (that updates the environment) before this fixes the problem. Maybe our discovery needs to be widened to include `sys.executable`?
> fix: make sure pyodide works without setup

- docs/options.md
Just a tiny doc fix I found while looking through the docs.
> DOC: Fix bug with link

- pyproject.toml
These xfails are being printed as tracebacks on every test run. Since they are known to not work, let's hide them for now.
> tests: don't print xfails

- cibuildwheel/macos.py
- cibuildwheel/windows.py
Fix https://github.com/pypa/cibuildwheel/issues/1877. Should be fixed by https://github.com/astral-sh/uv/pull/4289, but putting the correct path here is better anyway.
> fix: specify full path to non-venv Python

- cibuildwheel/pyodide.py
- test/conftest.py
- test/test_before_test.py
- test/test_dependency_versions.py
- test/test_pep518.py
> chore(tests): run a project with tests using `build[uv]` frontend

- docs/options.md
This PR fixes a small mistake in the docs where the extra in `build[uv]` would not be escaped properly; unexpectedly forming a markdown link.
> docs: properly escape extra in `build[uv]`

- cibuildwheel/linux.py
pip 24.1 is now embedded in virtualenv
> chore: remove pip beta workaround

- cibuildwheel/resources/build-platforms.toml
- docs/faq.md
I just hit https://github.com/pypa/cibuildwheel/issues/1278 :
https://github.com/h5py/h5py/actions/runs/9472096444/job/26096834822#step:9:483
```
error: dlopen(/Users/runner/work/h5py/h5py/cache/hdf5/1.12.2-arm64/lib/libhdf5.dylib, 0x0006): tried:
... '/Users/runner/work/h5py/h5py/cache/hdf5/1.12.2-arm64/lib/libhdf5.200.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```
Using the suggestion from https://github.com/pypa/cibuildwheel/issues/1278#issuecomment-2052099631 in https://github.com/h5py/h5py/pull/2444/commits/87cf54c343e70e43885aa876aa1fee131726cb2a fixes it:
https://github.com/h5py/h5py/actions/runs/9472215836/job/26097237985?pr=2444#step:9:179
@cretz do you want to open a quick PR instead so you can get credit (and blame 😄 ) for this …
> DOC: Document macOS 3.8 arm64 workaround

- .circleci/config.yml
- .circleci/prepare.sh
- .gitlab-ci.yml
- CI.md
- azure-pipelines.yml
- examples/azure-pipelines-minimal.yml
- examples/circleci-minimal.yml
- examples/gitlab-minimal.yml
- CircleCI:
move to python 3.12
CircleCI does not support Intel macOS runners anymore.
c.f. https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718
- Azure Pipelines:
macOS-11 has been removed. move to macOS-12
- GitLab:
Windows tag has changed.
move to python 3.12
fix #1897
> fix(ci): CircleCI / Azure Pipelines / GitLab

- docs/options.md
- test/test_testing.py
> chore: remove nosetests from tests and docs

- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- docs/options.md
Fixing #1887. I didn't special case chained short flags, like `-xn` or `-nx`, maybe we should?
> fix: support --no-isolation with build[uv]

- cibuildwheel/errors.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/pyodide.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
- test/test_custom_repair_wheel.py
- test/test_pure_wheel.py
Part of the effort for #1857 / #1873. Follow-up on #1719.
> chore: move `AlreadyBuiltWheelError` & `NonPlatformWheelError` to `errors.py`

- .github/workflows/test.yml
In preparation for #1912, always use the latest stable python to run nox  in the lint job.
> chore: use python from setup-python step to run nox

- README.md
- docs/changelog.md
This fixes a link to the correct PR number.
The description for https://github.com/pypa/cibuildwheel/releases/tag/v2.19.2 can be manually edited using the web UI.
> DOC: fix link to correct PR number

- examples/cirrus-ci-intel-mac.yml
- examples/cirrus-ci-minimal.yml
- examples/gitlab-with-qemu.yml
- examples/travis-ci-deploy.yml
- examples/travis-ci-minimal.yml
- examples/travis-ci-test-and-deploy.yml
Towards #1912 
There's also the EOL of python 3.8 coming soon so we'd better have examples using the latest stable version of Python to run cibuildwheel.
> chore: update examples to use python 3.12

- cibuildwheel/windows.py
- pyproject.toml
- unit_test/get_platform_test.py
This fixes #1861 and any other build setups which make use of `setuptools._distutils.util.get_platform()` on windows
- Uses `dict` lookup pattern analog to many other places within the code
- Only sets the variable if it has not already been set manually
- Will overwrite a pre-set `VSCMD_ARG_TGT_ARCH=""`
- Tests `monkeypatch` the environment before calling `setuptools._distutils.util.get_platform()` and validating returned platform
- Tests are set to only run on windows
- monkeypatching `os.name` in a tight context worked locally (Win11 + WSL2 + Ubunutu 22.04), but fails in pipeline on github actions
- all tests pass on github actions windows runner but tests targeting arm64 fail on azure pipeline. I'm assuming this is a weird, azure-specific thing in their environment and have set the …
> set VSCMD_ARG_TGT_ARCH based on targetted architecture

- cibuildwheel/windows.py
uv 0.2.25+ does not work with PyPy 3.8 on Windows
Given PyPy 3.8 is EOL, just disable uv for this config rather than ask for it to be supported again in uv.
> fix: do not use uv on Windows PyPy 3.8

- docs/contributing.md
A minor update to the contributing guide. `nox -s docs` is currently configured to build and serve the docs, so `nox -s docs -- serve` causes an error.
> docs: fix nox docs command

- cibuildwheel/__main__.py
- cibuildwheel/options.py
- docs/options.md
- test/test_0_basic.py
Adds a `CIBW_ALLOW_EMPTY` environment variable as an alternative to passing `--allow-empty`.
Closes #1922
> feat: add `CIBW_ALLOW_EMPTY` environment variable

- README.md
- cibuildwheel/util.py
- unit_test/build_selector_test.py
- unit_test/linux_build_steps_test.py
- unit_test/option_prepare_test.py
Enable building with CPython 3.13 by default, no longer requiring `prerelease_pythons` flag to be set true.
Merge after https://github.com/pypa/cibuildwheel/pull/1949 is merged.
Builds upon last-year PRs: https://github.com/pypa/cibuildwheel/pull/1226 and https://github.com/pypa/cibuildwheel/pull/1565.
> Build CPython 3.13 by default

- cibuildwheel/__main__.py
- test/utils.py
- unit_test/main_tests/main_platform_test.py
Empty environment variables should be treated like unset environment variables where possible. This wasn't done for `CIBW_PLATFORM` #1965 (before `pyodide`, there wasn't much reason to set this on CI).
> fix: support empty CIBW_PLATFORM

- CI.md
- appveyor.yml
- examples/appveyor-minimal.yml
fix issues with AppVeyor seen while working on https://github.com/pypa/cibuildwheel/pull/1961
> fix: AppVeyor CI tests & sample

- .travis.yml
- test/test_emscripten.py
fix issues with Travis CI seen while working on #1961
> fix: TravisCI failures & status

- .github/workflows/test.yml
remove specific code to install podman (which does not require specific APT sources since ubuntu 22.04)
> chore(ci): podman is now pre-installed on GHA runners

- cibuildwheel/options.py
- unit_test/options_test.py
- unit_test/options_toml_test.py
Fix for #1803, where the method used for merging the `config-settings` option - string concatenation - was of little use.
I broke out the TableFmt object into a protocol-like object called OptionFormat, where the formatting and merge rules can be customised more deeply. This is more explicit, and lets us be a bit more precise with how TOML object get converted into the options.
I intend to use the flexibility of the OptionsFormat structure to tackle the remaining abiguity around environment variable quoting, as seen in the xfails in the `options_test.py` unit test and discussed in #1271.
> Customise merge behaviour depending on option. Fix #1803

- .circleci/prepare.sh
- .cirrus.yml
- .github/workflows/test.yml
- .gitlab-ci.yml
- .travis.yml
- appveyor.yml
- azure-pipelines.yml
- bin/run_tests.py
- cibuildwheel/architecture.py
- cibuildwheel/errors.py
- cibuildwheel/linux.py
- cibuildwheel/oci_container.py
- test/test_container_engine.py
- unit_test/oci_container_test.py
- unit_test/option_prepare_test.py
This allows to always pass `--platform` to the OCI engine thus fixing issues with multiarch images.
It also allows to use `docker cp` instead of system tar workaround.
fix #1771
fix #1957
fix #1962
close #1968
Last time this was attempted, it failed on some CI (c.f. https://github.com/pypa/cibuildwheel/pull/1773), let's check the status now.
> fix: enforce minimum version of docker/podman

- cibuildwheel/macos.py
- cibuildwheel/windows.py
`uv` was still used in `setup_python` on Windows even when `use_uv` was `False`.
This PR fixes `setup_python` to fallback to `build` frontend name instead of `build[uv]` in that case.
Added `can_use_uv` function to make sure wether or not `uv` is usable in a single place rather than duplicate the checks (and potentially forgetting one out of two if the conditions were to change).
> fix: do not use `uv` to setup python on windows when conditions are not met

- cibuildwheel/errors.py
- cibuildwheel/oci_container.py
- cibuildwheel/util.py
- unit_test/oci_container_test.py
- unit_test/utils_test.py
This PR addresses two separate issues sometimes encountered with Podman:
1. Sometimes, the `podman` cli utility does not support the `version` subcommand, whose output is currently used for ascertaining the "APIVersion".
2. Podman's reported "Client.APIVersion" sometimes includes characters that the Version class cannot parse (e.g., "4.9.4-rhel")
For clients whose `podman version -f "{{json .}}"` command does function as expected, the reported "Version" and "APIVersion" values seem to match; so, this PR implements an alternate method of determining Podman's version that seems to behave more reliably across distributions + architectures: we use regex to match a valid version pattern from the single-line output of the `podman --version` command.
fix #2020 
*edit: rewritten for clarity
> fix: more reliably validate Podman API version 

- cibuildwheel/__main__.py
- cibuildwheel/options.py
We are getting annotations, removing the issues.
> chore: remove a couple of things pylint is unhappy about

- test/test_abi_variants.py
With bdist_wheel becoming a first-class citizen command of setuptools, this trick might not work in the future.
> fix: do not subclass wheel.bdist_wheel command in ABI3 test

- README.md
- docs/cpp_standards.md
- docs/options.md
> docs: update for 3.13.0 final

- cibuildwheel/linux.py
- cibuildwheel/oci_container.py
3.8 is EOL, move to 3.9
Also use Python 3.9 for utility python in oci_container.
As a side note, 3.9 is the last version available across all images being used in cibuildwheel tests.
> linux: use Python 3.9 in before_all

- cibuildwheel/errors.py
- cibuildwheel/macos.py
Close #2038. And help with #2034.
> docs: print a couple slighly more detailed error messages

- cibuildwheel/oci_container.py
> fix: re-raise `subprocess.CalledProcessError` when `uname -m` fails on arm

- README.md
- cibuildwheel/__main__.py
> chore: add warning when running cibuildwheel with python<3.11

- cibuildwheel/errors.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- docs/options.md
Fix #1934
- **Fix bug in docs for running abi3audit in repair-wheel-command on windows**
- **Better error message for misconfigured repair-wheel-command**
> `repair-wheel-command` docs and error message improvements

- README.md
Closes #2069
Add missed `github` information in travis link (travis allows running from multiple repo provides)
> Fix travis link in readme

- unit_test/main_tests/main_options_test.py
Caught with https://github.com/crate-ci/typos.
This would probably only be an issue if there was an ambient `CIBW_CONFIG_SETTINGS` envvar that'd conflict with the test.
> tests: fix CIBW_CONFIG_SETTIGNS typo in test

- cibuildwheel/linux.py
As reported in https://github.com/pypa/cibuildwheel/pull/2062#issuecomment-2448112031, the error message needs to be fixed.
The failure can also be seen in another build on Travis CI: https://app.travis-ci.com/github/pypa/cibuildwheel/jobs/627703558?serverType=git
2 options proposed:
- If interpreter presence check fails, check the result of `manylinux-interpreters ensure ...` to decide on the error message to present to the user.
- Don't run the presence check when `manylinux-interpreters` is available and rely only on it to pass or fail properly.
> fix: error message when `manylinux-interpreters ensure ...` failed

- bin/generate_schema.py
- cibuildwheel/options.py
- cibuildwheel/resources/cibuildwheel.schema.json
- cibuildwheel/resources/defaults.toml
- cibuildwheel/util.py
- docs/options.md
- unit_test/build_selector_test.py
- unit_test/main_tests/main_platform_test.py
- unit_test/options_test.py
Close https://github.com/pypa/cibuildwheel/issues/2045. Adds `enable`, deprecates the old way of specifying these (remove in 3.0).
> feat: adding enable

- cibuildwheel/macos.py
- cibuildwheel/pyodide.py
- cibuildwheel/util.py
- cibuildwheel/windows.py
> fix: capture `stderr` in `utils.call` when `capture_stdout` is `True`

- .cirrus.yml
- examples/cirrus-ci-intel-mac.yml
- examples/cirrus-ci-minimal.yml
Use `ghcr.io/cirruslabs/macos-runner:sonoma` instead of `ghcr.io/cirruslabs/macos-sonoma-xcode` which is not supported anymore.
> fix: update the macOS image used on Cirrus CI

- docs/contributing.md
- docs/options.md
Hello
I fixed several spelling issues.
Br, Elias.
> Docs: fix update scripts usage

- .gitlab-ci.yml
Update for GitLab missed in #2064.
> ci: update gitlab for dependency-groups

- .github/workflows/test.yml
- cibuildwheel/pyodide.py
- cibuildwheel/resources/build-platforms.toml
- cibuildwheel/resources/constraints-pyodide312.txt
- noxfile.py
- test/test_emscripten.py
This PR has been split off from #2002, where it has been attempted to allow the use of a build-time flag to build and test a Pyodide version that is not available with cibuildwheel, since the cibuildwheel version couples the Pyodide version available within it.
This PR is, rather, more limited in its approach. The key changes here are:
- Post https://github.com/pyodide/pyodide/pull/4882, [`pyodide-build` is now hosted in its own repository](https://github.com/pyodide/pyodide-build), and updates to it are not made in sync with updates to the Pyodide version, allowing `pyodide-build` to move faster with changes to it. Hence, the `pyodide-build` version (currently at 0.29.0) is now what is used to fetch the Pyodide xbuildenv for Pyodide builds.
- Updated to the recently released [Pyodide …
> Updates for Pyodide builds after `pyodide-build` was unvendored

- .pre-commit-config.yaml
- cibuildwheel/_compat/typing.py
- cibuildwheel/typing.py
- pyproject.toml
Hi! I just released Ruff 0.8.0. This release removes `PT004`, which had been deprecated for a few releases, so Ruff 0.8.0 would have started emitting warnings when linting `cibuildwheel` due to the fact that you have `PT004` explicitly ignored in your Ruff config.
This PR gets rid of `PT004` from your Ruff config. There's also some additional changes made here due to the stabilisation of [`unsorted-dunder-all`](https://docs.astral.sh/ruff/rules/unsorted-dunder-all/) (`RUF022`) in this release -- let me know if these are unwelcome, and I can add them to the `tool.ruff.lint.ignore` list.
> Bump Ruff to 0.8.0

- cibuildwheel/resources/cibuildwheel.schema.json
We missed a final `nox -s generate_schema` before merging  #2048
> fix: cibuildwheel.schema.json

- README.md
The link to the deprecated option does not work anymore (and even if it were working, we want to advertise the non deprecated option).
> docs: use non deprecated option for free-threading

- docs/options.md
Copy and pasted this, and found there's a typo.
> docs: fix typo in enable

- pyproject.toml
- test/conftest.py
Let's see if we can speed-up linux CI by warming-up docker images.
This helps locally but I have a very slow Internet connection so it might not apply here.
> ci: warm-up docker images

- cibuildwheel/resources/build-platforms.toml
- cibuildwheel/resources/constraints-pyodide312.txt
https://github.com/pyodide/pyodide/releases/tag/0.27.0 is now available on 01-01-2025, and so are the [new xbuildenvs](https://github.com/pyodide/pyodide/blob/1e37b7fce9b89f82cd39b7578317c41ddf0aa947/pyodide-cross-build-environments.json#L2-L9) for it. This PR updates the Pyodide version from 0.26.4 to 0.27.0, and the version of `pyodide-build` from 0.29.0 to 0.29.2.
> Bump to Pyodide 0.27

- .github/workflows/update-dependencies.yml
`app_id`/`private_key` are deprecated, we shall use `app-id`/`private-key` instead.
> chore: fix deprecations warnings in update-dependencies workflow

- .github/workflows/test.yml
- bin/generate_schema.py
- cibuildwheel/__main__.py
- cibuildwheel/options.py
- cibuildwheel/resources/cibuildwheel.schema.json
- cibuildwheel/resources/defaults.toml
- cibuildwheel/util.py
- docs/options.md
- test/utils.py
- unit_test/build_selector_test.py
- unit_test/main_tests/conftest.py
- unit_test/main_tests/main_options_test.py
- unit_test/main_tests/main_platform_test.py
- unit_test/option_prepare_test.py
- unit_test/options_test.py
Drop deprecated options related to `CIBW_ENABLE`.
> chore: drop deprecated options related to `CIBW_ENABLE`

- bin/generate_schema.py
This was in the generated file, but missing from the generation script.
> Add missing schema for test-sources

- .travis.yml
- CI.md
- cibuildwheel/architecture.py
- examples/github-with-qemu.yml
- examples/travis-ci-deploy.yml
- examples/travis-ci-minimal.yml
- examples/travis-ci-test-and-deploy.yml
- test/test_manylinuxXXXX_only.py
- test/test_musllinux_X_Y_only.py
- test/test_testing.py
- test/utils.py
- unit_test/architecture_test.py
- unit_test/main_tests/conftest.py
- unit_test/oci_container_test.py
This depends on aarch32 EL0 support and thus is done conditionally.
This uses a `linux32` call to check for support.
Things weren't working well on Travis CI for some reason. Given all examples are using LXD, I updated tests to use that as well and running armv7l  does not seem supported on that infrastructure.
The feature was first requested in https://github.com/pypa/cibuildwheel/pull/2135#discussion_r1924179661
> feat: add armv7l in auto_archs when running on aarch64

- .github/workflows/test.yml
- .pre-commit-config.yaml
- noxfile.py
- pyproject.toml
Using new features in nox 2025. This can now be run with `uv run`, `pipx run`, `hatch run`, etc.
> chore: use nox 2025.2.9 features

- bin/update_how_it_works_image.py
- cibuildwheel/__main__.py
- cibuildwheel/util/file.py
- test/test_custom_repair_wheel.py
Use `exist_ok` and `missing_ok` in pathlib operations where we can.
I didn't do an exhaustive audit of pathlib usage, but I did look at places where the code was using `path.exists()`. There's still a couple of places with this pattern:
```python
if path.exists():
shutil.rmtree(path)
```
I don't think there's an elegant solution that will work across Python versions currently, although in 3.13 I think one can do:
```python
try:
shutil.rmtree(path)
except FileNotFoundError:
pass
```
Because: "*Changed in version 3.13*: `rmtree()` now ignores `FileNotFoundError` exceptions for all but the top-level path." (https://docs.python.org/3.13/library/shutil.html#shutil.rmtree)
Fixes #2279.
> fix: avoid races in filesystem ops

- cibuildwheel/__main__.py
- cibuildwheel/architecture.py
- cibuildwheel/linux.py
- cibuildwheel/logger.py
- cibuildwheel/macos.py
- unit_test/main_tests/main_platform_test.py
This makes them appear GHA annotations in CI logs, which makes them easier to spot. I've also added the "cibuildwheel: " prefix to those errors, I think it helps when viewing a log to know which tool is talking to you - it can be difficult to understand with build tools.
> feat: Print FatalError messages using Logger

- test/utils.py
c.f. last build on main
`linux32 uname -m` fails on Cirrus CI
> fix(ci): Cirrus CI does not allow armv7l builds on aarch64

- cibuildwheel/logger.py
- cibuildwheel/options.py
> fix: warn on deprecated images being set

- .travis.yml
As mentioned in #2290, start reducing Travis-CI testing on x86_64.
With the 1 concurrent job plan, it should allow to get a faster status for Pull Requests.
> chore: only build on push to main for Travis CI

- cibuildwheel/options.py
- unit_test/options_test.py
The `musllinux_1_1 ` warning was not triggered, rework a bit the check and add some unit tests.
> fix: image deprecation warning

- cibuildwheel/ios.py
- cibuildwheel/linux.py
- cibuildwheel/macos.py
- cibuildwheel/windows.py
- docs/options.md
- test/test_before_build.py
This is another thing we planned for 3.0, I think.
> feat: use build by default

- docs/faq.md
- docs/platforms/macos.md
> Doc: add a note about Rustc's minimum MACOSX_DEPLOYMENT_TARGET requirement

- cibuildwheel/venv.py
This will fix https://github.com/pypa/cibuildwheel/issues/2327. `uvx git+https://github.com/henryiii/cibuildwheel@henryiii/fix/uvx --only cp312-pyodide_wasm32` does seem to pass with this.
Virtualenv can break if the `--python` argument is a symlink.
> fix: always resolve --python argument

- cibuildwheel/__main__.py
- cibuildwheel/options.py
- cibuildwheel/platforms/__init__.py
- cibuildwheel/platforms/ios.py
- cibuildwheel/platforms/linux.py
- cibuildwheel/platforms/macos.py
- cibuildwheel/platforms/pyodide.py
- cibuildwheel/platforms/windows.py
- cibuildwheel/selector.py
- test/test_0_basic.py
- test/utils.py
- unit_test/get_platform_test.py
- unit_test/linux_build_steps_test.py
- unit_test/main_tests/conftest.py
- unit_test/main_tests/main_options_test.py
- unit_test/option_prepare_test.py
- unit_test/options_test.py
Implementation of an idea from https://github.com/pypa/cibuildwheel/pull/2070#issuecomment-2676888930
cibuildwheel will error out if the `build` config contains something that it doesn't recognise. For `skip` and `test-skip`, it just prints a warning.
This is to highlight misconfiguration as seen in #2070. Notably, the set of identifiers that cibuildwheel will consider is not dependent on platform, so users can still do a global CIBW_BUILD that's shared across platforms.
Also in this PR, I wanted to iterate through platform modules, and so decided it was time to factor them out into their own package.
I'll keep this draft to merge #2286 first, since that adds a new platform.
> feat: stricter selector parsing, refactor to `platforms` module

- cibuildwheel/options.py
- cibuildwheel/resources/defaults.toml
- docs/options.md
- test/test_container_images.py
- test/utils.py
- unit_test/main_tests/main_options_test.py
- unit_test/option_prepare_test.py
- unit_test/options_toml_test.py
fixes #1772 
closes #1988
The rational for doing this is in #1988 with some timeline discussions in #1772 & #2047.
> feat: move default manylinux build to manylinux_2_28

- .github/workflows/test.yml
- bin/run_tests.py
- pyproject.toml
- test/test_0_basic.py
- test/test_ios.py
The iOS test suite added by #2286 has proven to be unstable in GitHub Actions CI, failing ~50% of the time. On deeper investigation, the issue appears to be CPU overloading on the CI machine. 
The integration tests run multhreaded using xdist; the ARM64 test machine reports 3 CPUs, and so 3 test threads are started. The iOS tests are isolated into a load group, resulting in the iOS tests being isolated to a single worker; but at the same time, the other two CPUs are allocated other macOS tests to run. The iOS test is itself a multi-process, multi-threaded build, calling Xcode, the iOS Simulator, and the macOS logging infrastructure; when the 2 remaining processes are at 100% utilisation building other tests, it's possible for the process of compiling the iOS project and booting a …
> Correct Github Actions CI instability for iOS.

- .github/workflows/test.yml
`tonistiigi/binfmt:latest` has been updated and the workaround should not be needed anymore.
close #2257
> ci: revert QEMU workaround

- cibuildwheel/frontend.py
- docs/options.md
- unit_test/options_test.py
See https://github.com/pypa/cibuildwheel/issues/2338.
This makes the verbosity setting a bit more useful on other backends. This tries to map the current `pip` meanings to other backends. The key changes are:
* `<0` will support `uv` (#2322), `build` continues to produce a warning. This is a feature that's been requested before for build, btw.
* `1` continues to do nothing on non-`pip` backends
* 2+ now passes multiple `-v` to non-pip backends, since both build and uv support adding extra resolving info (similar to pip's `-vv`) if passing `-v`.
> fix: support wider range of verbosity settings on other build backends

- azure-pipelines.yml
- bin/run_tests.py
- cibuildwheel/platforms/ios.py
- cibuildwheel/platforms/macos.py
- cibuildwheel/platforms/pyodide.py
- cibuildwheel/platforms/windows.py
- cibuildwheel/venv.py
Pulled out from #2322 to simplify that one. Passes the actual Path or None instead of passing the flags and then parsing the argument back out (!). Also switches to using the URI, but I could do that in 2322 instead if there are any issues (edit: seems fine!).
> refactor: pull out dependency_constraint

- cibuildwheel/platforms/macos.py
- cibuildwheel/platforms/windows.py
- cibuildwheel/venv.py
As mentioned in https://github.com/pypa/cibuildwheel/pull/2347#discussion_r2029821701
Rework the way test venvs are created to reuse the same mechanisms as build venvs.
> chore: rework virtual environments creation for tests

- .cirrus.yml
- examples/cirrus-ci-minimal.yml
The macos_arm64_cp38 job fails because it selects 0 serial tests.
The macos_arm64 was failing on iOS tests, move to `sequoia` in order to fix those.
> fix(CI): Cirrus CI macos jobs

- .github/workflows/test.yml
- README.md
- azure-pipelines.yml
- bin/update_pythons.py
- cibuildwheel/logger.py
- cibuildwheel/platforms/macos.py
- cibuildwheel/platforms/windows.py
- cibuildwheel/resources/build-platforms.toml
- cibuildwheel/selector.py
- docs/options.md
- test/conftest.py
- test/test_0_basic.py
- test/test_abi_variants.py
- test/test_before_all.py
- test/test_before_build.py
- test/test_before_test.py
- test/test_dependency_versions.py
- test/test_pep518.py
- test/test_testing.py
- test/utils.py
- unit_test/linux_build_steps_test.py
- unit_test/main_tests/main_options_test.py
- unit_test/option_prepare_test.py
This PR adds support for GraalPy.
A couple of questions:
1. GraalPy is not included in manylinux images, so I added a facility to download Pythons there as well. Does that seem ok?
2. I couldn't find a way to exclude GraalPy by default - I'm not sure, but maybe it would be good to be conservative here and let people opt-in to building wheels on GraalPy via the `CIBW_BUILD` variable explicitly.
> Support GraalPy

- .github/workflows/test.yml
- bin/generate_schema.py
- bin/run_tests.py
- bin/sample_build.py
- cibuildwheel/__main__.py
- pyproject.toml
- test/test_projects/__main__.py
Also turning off abbreviations, and 3.14+'s suggestions for choices.
Adds the 3.14 classifier and runs tests on 3.14 (linux only).
> fix: support Python 3.14's color CLI

- .github/workflows/test.yml
- docs/contributing.md
- test/conftest.py
- test/test_0_basic.py
- test/test_abi_variants.py
- test/test_before_build.py
- test/test_before_test.py
- test/test_build_frontend_args.py
- test/test_container_engine.py
- test/test_container_images.py
- test/test_cpp_standards.py
- test/test_dependency_versions.py
- test/test_emulation.py
- test/test_environment.py
- test/test_ios.py
- test/test_linux_python.py
- test/test_macos_archs.py
- test/test_manylinuxXXXX_only.py
- test/test_musllinux_X_Y_only.py
- test/test_pep518.py
- test/test_troubleshooting.py
- test/test_wheel_tag.py
- test/test_windows.py
- test/utils.py
Apologies for another 3.x PR, this has been sitting in my local repo for a few days so I thought I'd polish it up.
Essentially, I find myself setting CIBW_ENABLE and CIBW_PLATFORM locally to run integration tests more and more, but as discussed previously, it's not very user friendly.
This necessitates a change from the `utils.platform` variable we had before to a `utils.get_platform()` function. But I think it's worth it, it also means we're not duplicating state between os.environ and `utils.platform`.
> Improve integration test options

- cibuildwheel/oci_container.py
- unit_test/oci_container_test.py
The OCIContainer handler includes a `copy_file` utility that can copy single files, and directories. It uses `cat` to copy a single file; however, if it is provided a deep path to a file (i.e., `path/to/file.py`), it attempts to copy the file to the destination path without first confirming that the destination path exists.
This PR modifies the containerised `copy_file` implementation to ensure that the target directory exists when copying a deep file reference
Fixes #2405.
> Ensure that deep paths exist before copying files.

- .travis.yml
- cibuildwheel/platforms/windows.py
- test/test_before_all.py
It seems there's something in the GraalPy build that isn't happy on a Travis windows machine - [example](https://app.travis-ci.com/github/pypa/cibuildwheel/jobs/632706288#L1358)
I've seen the same error on Cirrus too.
> [travis-ci] debugging ci failures on travis

- bin/update_pythons.py
The new Windows Python install manager was added to this page:
https://www.python.org/api/v2/downloads/release/?is_published=true
Which breaks our script. While we wait for beta 2 in manylinux, let's fix this. :)
> chore: fix update script to handle pymanager addition to page

- cibuildwheel/platforms/ios.py
- cibuildwheel/platforms/linux.py
- cibuildwheel/platforms/macos.py
- cibuildwheel/platforms/pyodide.py
- cibuildwheel/platforms/windows.py
- cibuildwheel/resources/testing_temp_dir_file.py
- cibuildwheel/util/resources.py
- docs/configuration.md
- docs/options.md
- test/test_abi_variants.py
- test/test_before_test.py
- test/test_emulation.py
- test/test_ios.py
- test/test_macos_archs.py
- test/test_pyodide.py
- test/test_testing.py
Fix https://github.com/pypa/cibuildwheel/issues/2406.
Alternative to #2419.
This approach restores the v2.x behaviour of running tests from a temp directory. That resolves the issues noted in #2406.
This also removes the ambiguity from https://github.com/pypa/cibuildwheel/pull/2363#issuecomment-2851205233 , so I've removed the restriction that iOS requires test-sources to be set - in this world, we can use the inclusion of the `{project}` placeholder in `test-command` as a signal that users haven't configured things correctly for iOS. Failing that, the `test_fail.py` script that a test runner (pytest) will find can prompt the user to use `test-sources`.
> Revert to running tests from from a temp dir when test-sources is unset

- cibuildwheel/platforms/linux.py
- cibuildwheel/platforms/macos.py
- cibuildwheel/platforms/pyodide.py
- cibuildwheel/platforms/windows.py
- docs/options.md
- test/test_testing.py
Not really needed now. This doesn't remove the test-environment, just PYTHONSAFEPATH.
> fix: drop PYTHONSAFEPATH

- .cirrus.yml
- README.md
- cibuildwheel/platforms/windows.py
- test/test_ios.py
Fix the build on `main`. 
Cirrus has a problem running the simulator, see a recent build on main, for example:
https://cirrus-ci.com/task/6394806932340736?logs=run_cibuildwheel_tests#L1832
I've removed the support tick from cirrus in the readme too, until/unless we can figure this out. 
cc @freakboy3742
Sometimes vsdevcmd can print an error to console while it works. This messed up the environment JSON blob, so it's saved to a file instead.
> Debug Cirrus CI testing

- bin/generate_schema.py
- cibuildwheel/resources/cibuildwheel.schema.json
This was a workaround for a bug in validate-pyproject, but that bug was fixed some time ago, so we can use the standard line here now. 3.0 seems like a good time to fix this.
> fix: use standard schema line

- cibuildwheel/platforms/ios.py
- cibuildwheel/util/cmd.py
- test/test_ios.py
This should add support for multiple commands on iOS.
Remember to select "hide whitespace" when viewing the diff. :)
Fix #2423.
CC @freakboy3742
> feat: support multiple commands on iOS

- cibuildwheel/platforms/ios.py
- cibuildwheel/platforms/linux.py
- cibuildwheel/platforms/macos.py
- cibuildwheel/platforms/pyodide.py
- cibuildwheel/platforms/windows.py
- cibuildwheel/util/file.py
Critical fix before 3.0: test-sources should be relative to the project root, not the package directory. The package directory is always a subdirectory of the project directory, so this is more flexible.
By the way, on iOS, it might make sense to expand `{project}` to the relative path? While you normally do know it as well, I'm not sure what all the details are if you run directly on an SDist. (So test-sources work, `{project}`/`cwd()` should probably be the root of the SDist, would be good to verify)
No documentation change since this is how it's described in the docs already. :)
Fix #2436.
> fix: test-sources should use project dir

- .pre-commit-config.yaml
- .readthedocs.yml
- docs/main.py
- docs/options.md
- noxfile.py
- pyproject.toml
Close https://github.com/pypa/cibuildwheel/issues/2399. A little hacky for now.
> docs: color output for docs

- docs/platforms.md
Noted by @henryiii - iOS doesn't build all wheels by default. This was the behavior of an earlier version of the feature, but it was modified to "all for current architecture" before it was landed.
This updates the docs to match behavior.
Refs #2435.
> Correct documentation suggesting iOS builds all platforms by default.

- docs/options.md
> docs: warning about pyodide-version

- .cirrus.yml
- .github/workflows/test.yml
- azure-pipelines.yml
- examples/cirrus-ci-minimal.yml
- test/test_ssl.py
Reducing rebuilds when unrelated files change.
Trying to fix Cirrus CI GraalPy.
> ci: fix cirrus and reduce rebuilds

- .readthedocs.yml
There's now a binary (of b1, not b2, but that works), which downloads in a few seconds instead of building.
> ci: use uv python for docs (binary b1)

- .github/workflows/test.yml
- cibuildwheel/logger.py
- cibuildwheel/platforms/pyodide.py
Fixes pulled out of #2469. Pyodide was missing some logging constructs. (This is one reason to prefer context managers, much harder to forget to close them!)
> fix: pyodide missing some logging

- .github/CODEOWNERS
- README.md
I'd like to welcome a new team of platform maintainers to the cibuildwheel project! They are-
Russell Keith-Magee @freakboy3742 
Agriya Khetarpal @agriyakhetarpal 
Hood Chatham @hoodmane 
Gyeongjae Choi @ryanking13
Tim Felgentreff @timfel 
---
The platform maintainer team is a new initiative we've come up with. As cibuildwheel broadens its support into wider reaches of the ecosystem, we thought the project would benefit from a bit more specific expertise. So we're very pleased to be bringing in this talented bunch :)
> Welcome to our new platform maintainers!

- cibuildwheel/selector.py
- docs/options.md
- test/utils.py
This is no longer experimental in 3.13 beta 3, so we don't need an enable for it anymore. Someone can skip expliclity with `'cp31?t-*'` if they really don't want free-threaded wheels.
> feat: include free-threaded 3.14 by default

- bin/update_docker.py
- cibuildwheel/resources/defaults.toml
- cibuildwheel/resources/pinned_docker_images.cfg
- docs/options.md
- test/test_emulation.py
- test/utils.py
Images for RISC-V are now available in [pypa/manylinux](https://github.com/pypa/manylinux)
Wheels can't be pushed (yet) to PyPI so leaving the enable flag for now.
> feat: add default riscv64 images

- cibuildwheel/logger.py
- unit_test/wheel_print_test.py
close #2511
disclaimer: I have not attempted to run tests locally yet (I have very limited battery at the moment), but I did run typechecking via `pre-commit`, which correctly caught a mistake in my initial iteration, so I'm reasonably confident in this patch.
> BUG: hotfix report defects in logs and HTML summaries

- cibuildwheel/platforms/android.py
The cibuildwheel GitHub action executes cibuildwheel without activating its environment, so `wheel` is not on the PATH.
Example failure: https://github.com/pybind/pybind11/actions/runs/16500103683/job/46656018510
> fix(android): execute `wheel` via `sys.executable`

- cibuildwheel/__main__.py
- cibuildwheel/options.py
- unit_test/main_tests/main_options_test.py
> feat: add deprecation warning for `cpython-experimental-riscv64` enable

- cibuildwheel/resources/build-platforms.toml
Bumps the support package revisions for iOS. This includes:
* Python 3.13.5
* Python 3.14.0rc1
There are three notable bug fixes in these updates:
* Changes ensuring that the packages directory in the testbed is treated as a site-packages folder
* Inclusion of iOS shims for `strip`
* Corrections to the handling of `sysconfig.get_paths()` on Python 3.14
Fixes #2494.
> Bump iOS support package versions.

- pyproject.toml
- test/test_android.py
- test/test_ios.py
Adding a marker on the iOS test that flakes out sometimes.
I went with pytest-rerunfailures as it seems to be better maintained and gets about 5x the downloads vs. flaky. They are conflicting (same marker name), so you have to pick just one.
> tests: add flaky test handling

- test/test_ios.py
- unit_test/main_tests/conftest.py
- **tests: another iOS flaky spot**
- **tests: missing interceptions** (from #2519)
> tests: another iOS flaky spot

- cibuildwheel/platforms/pyodide.py
Fix the pyodide failures on main.
auditwheel-emscripten is already a dep of pyodide-build, and cibuildwheel doesn't use it directly. But by listing it in this "pip install" command, it was causing the resolver to backtrack to 0.25.0 of pyodide-build, because more recent versions of pyodide-build pin auditwheel-emscripten.
Pyodide folks, does that sound right to you?
> fix: pyodide build fails when dependency-versions is set

- bin/generate_schema.py
- bin/run_tests.py
- bin/sample_build.py
- cibuildwheel/__main__.py
These are now default True on 3.14rc1. Much nicer.
> chore: color and suggest_on_error are now default (3.14rc1+)

- bin/update_virtualenv.py
- cibuildwheel/resources/virtualenv.toml
See https://github.com/pypa/get-virtualenv/issues/51 for context.
Will hopefully be more robust.
> chore: Use the virtualenv release URL rather than the blob URL

- cibuildwheel/resources/build-platforms.toml
See https://github.com/pyodide/pyodide/releases/tag/0.28.2; needs pyodide/pyodide#5846 ~to be deployed~ (edit: done!).
> chore: bump to Pyodide 0.28.2

- .github/workflows/test.yml
- README.md
- azure-pipelines.yml
- docs/platforms.md
The 20250811 `macos-15` image update published by Microsoft has [caused problems with the CPython iOS testbed running on GitHub Actions and Azure runners](https://github.com/actions/runner-images/issues/12777). At this time, Microsoft's advice is "use `macos-14` instead". 
Unless Microsoft makes a configuration change that resolves/reverts the problem, this will require an update to CPython itself (see python/cpython#137973).
This PR switches the Azure runner image, and adds documentation warnings about the current state of macos-15 image support.
> Switch Azure Pipelines iOS image

- .github/workflows/test.yml
- README.md
- docs/platforms.md
- examples/github-deploy.yml
- examples/github-minimal.yml
- examples/github-pipx.yml
- examples/github-with-qemu.yml
See https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/; we can replace `macos-13` images with the new `macos-15-intel` runners, which will be phased out in 2027.
The `macos-14` images continue to be used and are not changed here, as `macos-15` continues to be broken for iOS wheel support.
> Replace the `macos-13` images with the `macos-15-intel` images (GHA)
